# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LeafBot.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QButtonGroup, QFrame,
    QGraphicsView, QGridLayout, QGroupBox, QHBoxLayout,
    QLabel, QLayout, QPushButton, QSizePolicy,
    QSpacerItem, QSpinBox, QVBoxLayout, QWidget)

class Ui_LeafBotForm(object):
    def setupUi(self, LeafBotForm):
        if not LeafBotForm.objectName():
            LeafBotForm.setObjectName(u"LeafBotForm")
        LeafBotForm.setWindowModality(Qt.WindowModality.WindowModal)
        LeafBotForm.resize(900, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LeafBotForm.sizePolicy().hasHeightForWidth())
        LeafBotForm.setSizePolicy(sizePolicy)
        LeafBotForm.setMaximumSize(QSize(1000, 800))
        palette = QPalette()
        brush = QBrush(QColor(59, 129, 26, 228))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(85, 255, 0, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(30, 83, 27, 228))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        brush3 = QBrush(QColor(29, 29, 29, 179))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(36, 31, 49, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(175, 175, 175, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        LeafBotForm.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        LeafBotForm.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"emblem-synchronized"))
        LeafBotForm.setWindowIcon(icon)
        LeafBotForm.setWindowOpacity(1.000000000000000)
        self.widget = QWidget(LeafBotForm)
        self.widget.setObjectName(u"widget")
        self.widget.setEnabled(True)
        self.widget.setGeometry(QRect(50, 40, 800, 721))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        brush6 = QBrush(QColor(181, 255, 125, 179))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        self.widget.setPalette(palette1)
        self.gridWidget = QWidget(self.widget)
        self.gridWidget.setObjectName(u"gridWidget")
        self.gridWidget.setGeometry(QRect(40, -10, 700, 611))
        self.gridWidget.setMinimumSize(QSize(500, 0))
        palette2 = QPalette()
        brush7 = QBrush(QColor(36, 142, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush7)
        brush8 = QBrush(QColor(255, 255, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        brush9 = QBrush(QColor(83, 110, 230, 179))
        brush9.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        self.gridWidget.setPalette(palette2)
        self.gridLayout_2 = QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalWidget = QWidget(self.gridWidget)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalWidget.setMinimumSize(QSize(550, 145))
        self.verticalWidget.setMaximumSize(QSize(550, 145))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.verticalWidget.setFont(font1)
        self.verticalLayout = QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widget1 = QWidget(self.verticalWidget)
        self.widget1.setObjectName(u"widget1")
        sizePolicy1.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy1)
        self.widget1.setMinimumSize(QSize(0, 10))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setKerning(True)
        self.widget1.setFont(font2)
        self.gridLayout = QGridLayout(self.widget1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_move_forward = QPushButton(self.widget1)
        self.pushButton_move_forward.setObjectName(u"pushButton_move_forward")
        sizePolicy1.setHeightForWidth(self.pushButton_move_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_forward.setSizePolicy(sizePolicy1)
        self.pushButton_move_forward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_forward.setMaximumSize(QSize(120, 25))
        palette3 = QPalette()
        brush10 = QBrush(QColor(237, 51, 59, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush10)
        brush11 = QBrush(QColor(255, 255, 255, 228))
        brush11.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.pushButton_move_forward.setPalette(palette3)
        self.pushButton_move_forward.setFont(font2)
        self.pushButton_move_forward.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_move_forward, 2, 3, 1, 1)

        self.pushButton_set_torque = QPushButton(self.widget1)
        self.pushButton_set_torque.setObjectName(u"pushButton_set_torque")
        sizePolicy1.setHeightForWidth(self.pushButton_set_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_set_torque.setSizePolicy(sizePolicy1)
        self.pushButton_set_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_set_torque.setMaximumSize(QSize(120, 25))
        palette4 = QPalette()
        brush12 = QBrush(QColor(119, 118, 123, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_set_torque.setPalette(palette4)
        self.pushButton_set_torque.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_set_torque, 3, 1, 1, 1)

        self.pushButton_read_servo = QPushButton(self.widget1)
        self.pushButton_read_servo.setObjectName(u"pushButton_read_servo")
        sizePolicy1.setHeightForWidth(self.pushButton_read_servo.sizePolicy().hasHeightForWidth())
        self.pushButton_read_servo.setSizePolicy(sizePolicy1)
        self.pushButton_read_servo.setMinimumSize(QSize(120, 25))
        self.pushButton_read_servo.setMaximumSize(QSize(120, 25))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_read_servo.setPalette(palette5)
        self.pushButton_read_servo.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_read_servo, 0, 1, 1, 1)

        self.pushButton_park_to_plant = QPushButton(self.widget1)
        self.pushButton_park_to_plant.setObjectName(u"pushButton_park_to_plant")
        sizePolicy1.setHeightForWidth(self.pushButton_park_to_plant.sizePolicy().hasHeightForWidth())
        self.pushButton_park_to_plant.setSizePolicy(sizePolicy1)
        self.pushButton_park_to_plant.setMinimumSize(QSize(120, 25))
        self.pushButton_park_to_plant.setMaximumSize(QSize(120, 25))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.pushButton_park_to_plant.setPalette(palette6)
        self.pushButton_park_to_plant.setFont(font2)
        self.pushButton_park_to_plant.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_park_to_plant, 0, 3, 1, 1)

        self.pushButton_off_torque = QPushButton(self.widget1)
        self.pushButton_off_torque.setObjectName(u"pushButton_off_torque")
        sizePolicy1.setHeightForWidth(self.pushButton_off_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_off_torque.setSizePolicy(sizePolicy1)
        self.pushButton_off_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_off_torque.setMaximumSize(QSize(150, 25))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_off_torque.setPalette(palette7)
        self.pushButton_off_torque.setFont(font2)
        self.pushButton_off_torque.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_off_torque, 3, 2, 1, 1)

        self.pushButton_pick_leaf = QPushButton(self.widget1)
        self.pushButton_pick_leaf.setObjectName(u"pushButton_pick_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_pick_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_pick_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_pick_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_pick_leaf, 2, 0, 1, 1)

        self.pushButton_detect_leaf = QPushButton(self.widget1)
        self.pushButton_detect_leaf.setObjectName(u"pushButton_detect_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_detect_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_detect_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_detect_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_detect_leaf, 0, 0, 1, 1)

        self.pushButton_train_eye2hand = QPushButton(self.widget1)
        self.pushButton_train_eye2hand.setObjectName(u"pushButton_train_eye2hand")
        sizePolicy1.setHeightForWidth(self.pushButton_train_eye2hand.sizePolicy().hasHeightForWidth())
        self.pushButton_train_eye2hand.setSizePolicy(sizePolicy1)
        self.pushButton_train_eye2hand.setMinimumSize(QSize(120, 25))
        self.pushButton_train_eye2hand.setMaximumSize(QSize(120, 25))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_train_eye2hand.setPalette(palette8)
        self.pushButton_train_eye2hand.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_train_eye2hand, 2, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.pushButton_move_backward = QPushButton(self.widget1)
        self.pushButton_move_backward.setObjectName(u"pushButton_move_backward")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward.setMaximumSize(QSize(120, 25))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.pushButton_move_backward.setPalette(palette9)
        self.pushButton_move_backward.setFont(font2)
        self.pushButton_move_backward.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_move_backward, 3, 3, 1, 1)

        self.pushButton_segment_leaf = QPushButton(self.widget1)
        self.pushButton_segment_leaf.setObjectName(u"pushButton_segment_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_segment_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_segment_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_segment_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_segment_leaf, 3, 0, 1, 1)

        self.pushButton_zero_position = QPushButton(self.widget1)
        self.pushButton_zero_position.setObjectName(u"pushButton_zero_position")
        sizePolicy1.setHeightForWidth(self.pushButton_zero_position.sizePolicy().hasHeightForWidth())
        self.pushButton_zero_position.setSizePolicy(sizePolicy1)
        self.pushButton_zero_position.setMinimumSize(QSize(120, 25))
        self.pushButton_zero_position.setMaximumSize(QSize(120, 30))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_zero_position.setPalette(palette10)
        self.pushButton_zero_position.setFont(font2)
        self.pushButton_zero_position.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_zero_position, 0, 2, 1, 1)

        self.pushButton_Imitation = QPushButton(self.widget1)
        self.pushButton_Imitation.setObjectName(u"pushButton_Imitation")
        sizePolicy1.setHeightForWidth(self.pushButton_Imitation.sizePolicy().hasHeightForWidth())
        self.pushButton_Imitation.setSizePolicy(sizePolicy1)
        self.pushButton_Imitation.setMinimumSize(QSize(120, 25))
        self.pushButton_Imitation.setMaximumSize(QSize(120, 25))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_Imitation.setPalette(palette11)
        self.pushButton_Imitation.setFont(font2)
        self.pushButton_Imitation.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_Imitation, 2, 2, 1, 1)


        self.verticalLayout.addWidget(self.widget1)


        self.gridLayout_2.addWidget(self.verticalWidget, 3, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalWidget = QWidget(self.gridWidget)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        self.horizontalWidget.setMinimumSize(QSize(500, 102))
        self.horizontalWidget.setMaximumSize(QSize(500, 102))
        self.horizontalLayout = QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.pushButton_3 = QPushButton(self.horizontalWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy1.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy1)
        self.pushButton_3.setMinimumSize(QSize(120, 25))
        self.pushButton_3.setMaximumSize(QSize(120, 25))
        palette12 = QPalette()
        brush13 = QBrush(QColor(255, 85, 127, 228))
        brush13.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        brush14 = QBrush(QColor(26, 95, 180, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_3.setPalette(palette12)
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        font3.setKerning(True)
        self.pushButton_3.setFont(font3)

        self.horizontalLayout.addWidget(self.pushButton_3)

        self.LeafBotLogo = QLabel(self.horizontalWidget)
        self.LeafBotLogo.setObjectName(u"LeafBotLogo")
        self.LeafBotLogo.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.LeafBotLogo.sizePolicy().hasHeightForWidth())
        self.LeafBotLogo.setSizePolicy(sizePolicy1)
        self.LeafBotLogo.setMinimumSize(QSize(100, 100))
        self.LeafBotLogo.setMaximumSize(QSize(100, 100))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Window, brush8)
        self.LeafBotLogo.setPalette(palette13)
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setHintingPreference(QFont.PreferFullHinting)
        self.LeafBotLogo.setFont(font4)
        self.LeafBotLogo.setTextFormat(Qt.TextFormat.PlainText)
        self.LeafBotLogo.setPixmap(QPixmap(u"logo.jpg"))
        self.LeafBotLogo.setScaledContents(True)
        self.LeafBotLogo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.LeafBotLogo)

        self.pushButton_21 = QPushButton(self.horizontalWidget)
        self.pushButton_21.setObjectName(u"pushButton_21")
        sizePolicy1.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy1)
        self.pushButton_21.setMinimumSize(QSize(120, 25))
        self.pushButton_21.setMaximumSize(QSize(120, 25))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        brush15 = QBrush(QColor(165, 29, 45, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush15)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush15)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush15)
        self.pushButton_21.setPalette(palette14)
        self.pushButton_21.setFont(font3)

        self.horizontalLayout.addWidget(self.pushButton_21)


        self.gridLayout_2.addWidget(self.horizontalWidget, 1, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.label_2 = QLabel(self.gridWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(16777215, 40))
        palette15 = QPalette()
        brush16 = QBrush(QColor(200, 65, 20, 228))
        brush16.setStyle(Qt.SolidPattern)
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        self.label_2.setPalette(palette15)
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setUnderline(True)
        font5.setKerning(True)
        self.label_2.setFont(font5)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 50, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 0, 1, 1)

        self.horizontalWidget_2 = QWidget(self.gridWidget)
        self.horizontalWidget_2.setObjectName(u"horizontalWidget_2")
        sizePolicy1.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy1)
        self.horizontalWidget_2.setMinimumSize(QSize(0, 600))
        self.horizontalWidget_2.setMaximumSize(QSize(600, 800))
        palette16 = QPalette()
        brush17 = QBrush(QColor(255, 255, 255, 179))
        brush17.setStyle(Qt.SolidPattern)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush17)
        brush18 = QBrush(QColor(173, 171, 168, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette16.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush17)
        palette16.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette16.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush18)
        self.horizontalWidget_2.setPalette(palette16)
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalGroupBox = QGroupBox(self.horizontalWidget_2)
        self.verticalGroupBox.setObjectName(u"verticalGroupBox")
        self.verticalGroupBox.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy1)
        palette17 = QPalette()
        brush19 = QBrush(QColor(90, 88, 84, 179))
        brush19.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush19)
        brush20 = QBrush(QColor(35, 35, 35, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush20)
        brush21 = QBrush(QColor(85, 85, 85, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipBase, brush21)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush19)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush20)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush21)
        brush22 = QBrush(QColor(0, 170, 0, 228))
        brush22.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush22)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush20)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush20)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush21)
        self.verticalGroupBox.setPalette(palette17)
        self.verticalGroupBox.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(255, 255, 127)\uff1b\n"
"	        }\n"
"")
        self.verticalLayout_2 = QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.pushButton_6 = QPushButton(self.verticalGroupBox)
        self.buttonGroup = QButtonGroup(LeafBotForm)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.pushButton_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy1)
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        brush23 = QBrush(QColor(254, 254, 254, 179))
        brush23.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        brush24 = QBrush(QColor(0, 0, 0, 228))
        brush24.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_6.setPalette(palette18)
        self.pushButton_6.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_6)

        self.pushButton_5 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_5)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy1)
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_5.setPalette(palette19)
        self.pushButton_5.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_5)

        self.pushButton_14 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_14)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy1)
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_14.setPalette(palette20)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(192, 184, 160);\n"
"	        }\n"
"")

        self.verticalLayout_2.addWidget(self.pushButton_14)

        self.pushButton_13 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_13)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy1)
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_13.setPalette(palette21)
        self.pushButton_13.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_13)

        self.pushButton_4 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy1)
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette22.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette22.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette22.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette22.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette22.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette22.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_4.setPalette(palette22)
        self.pushButton_4.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_4)

        self.pushButton_2 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy1)
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.ButtonText, brush24)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_2.setPalette(palette23)
        self.pushButton_2.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_2)


        self.horizontalLayout_2.addWidget(self.verticalGroupBox, 0, Qt.AlignmentFlag.AlignTop)

        self.verticalGroupBox_2 = QGroupBox(self.horizontalWidget_2)
        self.verticalGroupBox_2.setObjectName(u"verticalGroupBox_2")
        self.verticalGroupBox_2.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.verticalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_2.setSizePolicy(sizePolicy1)
        self.verticalGroupBox_2.setMinimumSize(QSize(0, 200))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush24)
        brush25 = QBrush(QColor(60, 255, 227, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush25)
        brush26 = QBrush(QColor(222, 221, 218, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette24.setBrush(QPalette.Active, QPalette.Dark, brush26)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette24.setBrush(QPalette.Inactive, QPalette.Dark, brush26)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush24)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush26)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        palette24.setBrush(QPalette.Disabled, QPalette.Dark, brush26)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush26)
        palette24.setBrush(QPalette.Disabled, QPalette.ButtonText, brush26)
        self.verticalGroupBox_2.setPalette(palette24)
        self.verticalLayout_3 = QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.spinBox = QSpinBox(self.verticalGroupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setEnabled(True)
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox.setPalette(palette25)
        self.spinBox.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox)

        self.spinBox_2 = QSpinBox(self.verticalGroupBox_2)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setEnabled(True)
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox_2.setPalette(palette26)
        self.spinBox_2.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox_2)

        self.spinBox_3 = QSpinBox(self.verticalGroupBox_2)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setEnabled(True)
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette27.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette27.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox_3.setPalette(palette27)
        self.spinBox_3.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox_3)

        self.spinBox_4 = QSpinBox(self.verticalGroupBox_2)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setEnabled(True)
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette28.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette28.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox_4.setPalette(palette28)
        self.spinBox_4.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox_4)

        self.spinBox_5 = QSpinBox(self.verticalGroupBox_2)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setEnabled(True)
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette29.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette29.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox_5.setPalette(palette29)
        self.spinBox_5.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox_5)

        self.spinBox_6 = QSpinBox(self.verticalGroupBox_2)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setEnabled(True)
        palette30 = QPalette()
        palette30.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette30.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette30.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        self.spinBox_6.setPalette(palette30)
        self.spinBox_6.setMaximum(180)

        self.verticalLayout_3.addWidget(self.spinBox_6)


        self.horizontalLayout_2.addWidget(self.verticalGroupBox_2, 0, Qt.AlignmentFlag.AlignTop)

        self.graphicsView = QGraphicsView(self.horizontalWidget_2)
        self.graphicsView.setObjectName(u"graphicsView")
        sizePolicy1.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy1)
        self.graphicsView.setMinimumSize(QSize(350, 250))
        self.graphicsView.setMaximumSize(QSize(350, 500))
        palette31 = QPalette()
        brush27 = QBrush(QColor(186, 186, 186, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette31.setBrush(QPalette.Active, QPalette.Base, brush27)
        palette31.setBrush(QPalette.Active, QPalette.Window, brush27)
        palette31.setBrush(QPalette.Inactive, QPalette.Base, brush27)
        palette31.setBrush(QPalette.Disabled, QPalette.Base, brush27)
        self.graphicsView.setPalette(palette31)
        self.graphicsView.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QFrame.Shape.Box)
        self.graphicsView.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView.setLineWidth(1)
        self.graphicsView.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView.setInteractive(True)

        self.horizontalLayout_2.addWidget(self.graphicsView, 0, Qt.AlignmentFlag.AlignTop)


        self.gridLayout_2.addWidget(self.horizontalWidget_2, 6, 0, 1, 1)


        self.retranslateUi(LeafBotForm)

        QMetaObject.connectSlotsByName(LeafBotForm)
    # setupUi

    def retranslateUi(self, LeafBotForm):
        LeafBotForm.setWindowTitle(QCoreApplication.translate("LeafBotForm", u"LeafBot", None))
        self.pushButton_move_forward.setText(QCoreApplication.translate("LeafBotForm", u"Move Forward", None))
        self.pushButton_set_torque.setText(QCoreApplication.translate("LeafBotForm", u"Set Torque", None))
        self.pushButton_read_servo.setText(QCoreApplication.translate("LeafBotForm", u"Read Servo", None))
        self.pushButton_park_to_plant.setText(QCoreApplication.translate("LeafBotForm", u"Park to Plant", None))
        self.pushButton_off_torque.setText(QCoreApplication.translate("LeafBotForm", u"Off Torque", None))
        self.pushButton_pick_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Pick Leaf", None))
        self.pushButton_detect_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Detect Leaf", None))
        self.pushButton_train_eye2hand.setText(QCoreApplication.translate("LeafBotForm", u"Train Eye2Hand", None))
        self.pushButton_move_backward.setText(QCoreApplication.translate("LeafBotForm", u"Move Backward", None))
        self.pushButton_segment_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Segment Leaf", None))
        self.pushButton_zero_position.setText(QCoreApplication.translate("LeafBotForm", u"Zero Position", None))
        self.pushButton_Imitation.setText(QCoreApplication.translate("LeafBotForm", u"Imitation", None))
        self.pushButton_3.setText(QCoreApplication.translate("LeafBotForm", u"Luanch All", None))
        self.LeafBotLogo.setText("")
        self.pushButton_21.setText(QCoreApplication.translate("LeafBotForm", u"Close All", None))
        self.label_2.setText(QCoreApplication.translate("LeafBotForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#248e00;\">LEAFBOT </span><span style=\" font-size:18pt; color:#ff0000;\">CONSOLE</span></p></body></html>", None))
        self.pushButton_6.setText(QCoreApplication.translate("LeafBotForm", u"J1", None))
        self.pushButton_5.setText(QCoreApplication.translate("LeafBotForm", u"J2", None))
        self.pushButton_14.setText(QCoreApplication.translate("LeafBotForm", u"J3", None))
        self.pushButton_13.setText(QCoreApplication.translate("LeafBotForm", u"J4", None))
        self.pushButton_4.setText(QCoreApplication.translate("LeafBotForm", u"J5", None))
        self.pushButton_2.setText(QCoreApplication.translate("LeafBotForm", u"J6", None))
    # retranslateUi

