# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LeafBot.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QFrame, QGraphicsView,
    QGridLayout, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)

class Ui_LeafBotForm(object):
    def setupUi(self, LeafBotForm):
        if not LeafBotForm.objectName():
            LeafBotForm.setObjectName(u"LeafBotForm")
        LeafBotForm.setWindowModality(Qt.WindowModality.WindowModal)
        LeafBotForm.resize(1000, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LeafBotForm.sizePolicy().hasHeightForWidth())
        LeafBotForm.setSizePolicy(sizePolicy)
        LeafBotForm.setMaximumSize(QSize(1000, 800))
        palette = QPalette()
        brush = QBrush(QColor(59, 129, 26, 228))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(85, 255, 0, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(30, 83, 27, 228))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        brush3 = QBrush(QColor(29, 29, 29, 179))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(175, 175, 175, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        LeafBotForm.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        LeafBotForm.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"emblem-synchronized"))
        LeafBotForm.setWindowIcon(icon)
        LeafBotForm.setWindowOpacity(1.000000000000000)
        self.widget = QWidget(LeafBotForm)
        self.widget.setObjectName(u"widget")
        self.widget.setEnabled(True)
        self.widget.setGeometry(QRect(90, 90, 800, 651))
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        brush6 = QBrush(QColor(181, 255, 125, 179))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        self.widget.setPalette(palette1)
        self.gridWidget = QWidget(self.widget)
        self.gridWidget.setObjectName(u"gridWidget")
        self.gridWidget.setGeometry(QRect(40, 10, 700, 591))
        self.gridWidget.setMinimumSize(QSize(500, 0))
        palette2 = QPalette()
        brush7 = QBrush(QColor(83, 110, 230, 179))
        brush7.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        self.gridWidget.setPalette(palette2)
        self.gridLayout_2 = QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalWidget = QWidget(self.gridWidget)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalWidget.setMinimumSize(QSize(500, 145))
        self.verticalWidget.setMaximumSize(QSize(500, 145))
        self.verticalLayout = QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.gridWidget1 = QWidget(self.verticalWidget)
        self.gridWidget1.setObjectName(u"gridWidget1")
        self.gridWidget1.setEnabled(True)
        sizePolicy.setHeightForWidth(self.gridWidget1.sizePolicy().hasHeightForWidth())
        self.gridWidget1.setSizePolicy(sizePolicy)
        self.gridWidget1.setMinimumSize(QSize(200, 25))
        self.gridWidget1.setMaximumSize(QSize(500, 200))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setKerning(True)
        self.gridWidget1.setFont(font1)
        self.gridLayout = QGridLayout(self.gridWidget1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_7 = QPushButton(self.gridWidget1)
        self.pushButton_7.setObjectName(u"pushButton_7")
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QSize(120, 30))
        self.pushButton_7.setMaximumSize(QSize(120, 50))
        palette3 = QPalette()
        brush8 = QBrush(QColor(255, 255, 255, 228))
        brush8.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_7.setPalette(palette3)
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        font2.setKerning(True)
        self.pushButton_7.setFont(font2)
        self.pushButton_7.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)

        self.pushButton_11 = QPushButton(self.gridWidget1)
        self.pushButton_11.setObjectName(u"pushButton_11")
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QSize(120, 30))
        self.pushButton_11.setMaximumSize(QSize(120, 25))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_11.setPalette(palette4)
        self.pushButton_11.setFont(font2)
        self.pushButton_11.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_11, 5, 2, 1, 1)

        self.pushButton_9 = QPushButton(self.gridWidget1)
        self.pushButton_9.setObjectName(u"pushButton_9")
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QSize(120, 30))
        self.pushButton_9.setMaximumSize(QSize(120, 25))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_9.setPalette(palette5)
        self.pushButton_9.setFont(font2)
        self.pushButton_9.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_9, 4, 2, 1, 1)

        self.pushButton_8 = QPushButton(self.gridWidget1)
        self.pushButton_8.setObjectName(u"pushButton_8")
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QSize(120, 30))
        self.pushButton_8.setMaximumSize(QSize(120, 25))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_8.setPalette(palette6)
        self.pushButton_8.setFont(font2)
        self.pushButton_8.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_8, 4, 0, 1, 1)

        self.pushButton_10 = QPushButton(self.gridWidget1)
        self.pushButton_10.setObjectName(u"pushButton_10")
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QSize(120, 30))
        self.pushButton_10.setMaximumSize(QSize(150, 25))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_10.setPalette(palette7)
        self.pushButton_10.setFont(font2)
        self.pushButton_10.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_10, 5, 0, 1, 1)

        self.pushButton_12 = QPushButton(self.gridWidget1)
        self.pushButton_12.setObjectName(u"pushButton_12")
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QSize(120, 30))
        self.pushButton_12.setMaximumSize(QSize(120, 25))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        self.pushButton_12.setPalette(palette8)
        self.pushButton_12.setFont(font2)
        self.pushButton_12.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 1)


        self.verticalLayout.addWidget(self.gridWidget1, 0, Qt.AlignmentFlag.AlignHCenter)


        self.gridLayout_2.addWidget(self.verticalWidget, 2, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.horizontalWidget = QWidget(self.gridWidget)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        self.horizontalWidget.setMinimumSize(QSize(500, 102))
        self.horizontalWidget.setMaximumSize(QSize(500, 102))
        self.horizontalLayout = QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton_3 = QPushButton(self.horizontalWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QSize(120, 25))
        self.pushButton_3.setMaximumSize(QSize(120, 25))
        palette9 = QPalette()
        brush9 = QBrush(QColor(255, 85, 127, 228))
        brush9.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush9)
        brush10 = QBrush(QColor(0, 255, 255, 179))
        brush10.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush9)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush9)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush9)
        brush11 = QBrush(QColor(38, 0, 255, 228))
        brush11.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        self.pushButton_3.setPalette(palette9)
        self.pushButton_3.setFont(font2)

        self.horizontalLayout.addWidget(self.pushButton_3)

        self.LeafBotLogo = QLabel(self.horizontalWidget)
        self.LeafBotLogo.setObjectName(u"LeafBotLogo")
        self.LeafBotLogo.setEnabled(True)
        sizePolicy.setHeightForWidth(self.LeafBotLogo.sizePolicy().hasHeightForWidth())
        self.LeafBotLogo.setSizePolicy(sizePolicy)
        self.LeafBotLogo.setMinimumSize(QSize(100, 100))
        self.LeafBotLogo.setMaximumSize(QSize(100, 100))
        palette10 = QPalette()
        brush12 = QBrush(QColor(255, 255, 255, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush12)
        self.LeafBotLogo.setPalette(palette10)
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setHintingPreference(QFont.PreferFullHinting)
        self.LeafBotLogo.setFont(font3)
        self.LeafBotLogo.setTextFormat(Qt.TextFormat.PlainText)
        self.LeafBotLogo.setPixmap(QPixmap(u"logo.jpg"))
        self.LeafBotLogo.setScaledContents(True)
        self.LeafBotLogo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.LeafBotLogo)

        self.pushButton = QPushButton(self.horizontalWidget)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QSize(120, 25))
        self.pushButton.setMaximumSize(QSize(120, 25))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        brush13 = QBrush(QColor(255, 0, 0, 179))
        brush13.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush13)
        brush14 = QBrush(QColor(255, 127, 127, 179))
        brush14.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush14)
        brush15 = QBrush(QColor(255, 63, 63, 179))
        brush15.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        brush16 = QBrush(QColor(127, 0, 0, 179))
        brush16.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(170, 0, 0, 179))
        brush17.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette11.setBrush(QPalette.Active, QPalette.BrightText, brush12)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush4)
        brush18 = QBrush(QColor(255, 127, 127, 217))
        brush18.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        brush19 = QBrush(QColor(255, 255, 220, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush19)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush4)
        brush20 = QBrush(QColor(0, 0, 0, 127))
        brush20.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush20)
#endif
        palette11.setBrush(QPalette.Active, QPalette.Accent, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.BrightText, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush19)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush20)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.Accent, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette11.setBrush(QPalette.Disabled, QPalette.BrightText, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush19)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush4)
        brush21 = QBrush(QColor(127, 0, 0, 89))
        brush21.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush21)
#endif
        brush22 = QBrush(QColor(255, 76, 76, 179))
        brush22.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Disabled, QPalette.Accent, brush22)
        self.pushButton.setPalette(palette11)
        self.pushButton.setFont(font2)

        self.horizontalLayout.addWidget(self.pushButton)


        self.gridLayout_2.addWidget(self.horizontalWidget, 1, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.horizontalWidget1 = QWidget(self.gridWidget)
        self.horizontalWidget1.setObjectName(u"horizontalWidget1")
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setMinimumSize(QSize(0, 250))
        self.horizontalWidget1.setMaximumSize(QSize(600, 400))
        palette12 = QPalette()
        brush23 = QBrush(QColor(255, 255, 255, 179))
        brush23.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush23)
        brush24 = QBrush(QColor(173, 171, 168, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush24)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush23)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush24)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush24)
        self.horizontalWidget1.setPalette(palette12)
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalGroupBox = QGroupBox(self.horizontalWidget1)
        self.verticalGroupBox.setObjectName(u"verticalGroupBox")
        self.verticalGroupBox.setEnabled(False)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy1)
        palette13 = QPalette()
        brush25 = QBrush(QColor(90, 88, 84, 179))
        brush25.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush25)
        brush26 = QBrush(QColor(35, 35, 35, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush26)
        brush27 = QBrush(QColor(85, 85, 85, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush27)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush25)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush26)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush27)
        brush28 = QBrush(QColor(0, 170, 0, 228))
        brush28.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush28)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush26)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush26)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush27)
        self.verticalGroupBox.setPalette(palette13)
        self.verticalGroupBox.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(255, 255, 127)\uff1b\n"
"	        }\n"
"")
        self.verticalLayout_2 = QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.pushButton_6 = QPushButton(self.verticalGroupBox)
        self.buttonGroup = QButtonGroup(LeafBotForm)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.pushButton_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        brush29 = QBrush(QColor(254, 254, 254, 179))
        brush29.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        brush30 = QBrush(QColor(0, 0, 0, 228))
        brush30.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_6.setPalette(palette14)
        self.pushButton_6.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_6)

        self.pushButton_5 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_5)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_5.setPalette(palette15)
        self.pushButton_5.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_5)

        self.pushButton_14 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_14)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_14.setPalette(palette16)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(192, 184, 160);\n"
"	        }\n"
"")

        self.verticalLayout_2.addWidget(self.pushButton_14)

        self.pushButton_13 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_13)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_13.setPalette(palette17)
        self.pushButton_13.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_13)

        self.pushButton_4 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_4.setPalette(palette18)
        self.pushButton_4.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_4)

        self.pushButton_2 = QPushButton(self.verticalGroupBox)
        self.buttonGroup.addButton(self.pushButton_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush29)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush29)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush29)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush30)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.pushButton_2.setPalette(palette19)
        self.pushButton_2.setFont(font)

        self.verticalLayout_2.addWidget(self.pushButton_2)


        self.horizontalLayout_2.addWidget(self.verticalGroupBox)

        self.verticalGroupBox_2 = QGroupBox(self.horizontalWidget1)
        self.verticalGroupBox_2.setObjectName(u"verticalGroupBox_2")
        self.verticalGroupBox_2.setEnabled(False)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.verticalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_2.setSizePolicy(sizePolicy2)
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush28)
        self.verticalGroupBox_2.setPalette(palette20)
        self.verticalLayout_3 = QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.lcdNumber = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QSize(50, 8))
        self.lcdNumber.setMaximumSize(QSize(60, 25))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber.setPalette(palette21)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber)

        self.lcdNumber_2 = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber_2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_2.setSizePolicy(sizePolicy)
        self.lcdNumber_2.setMinimumSize(QSize(50, 8))
        self.lcdNumber_2.setMaximumSize(QSize(60, 25))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber_2.setPalette(palette22)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setDigitCount(1)
        self.lcdNumber_2.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_2.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber_2)

        self.lcdNumber_4 = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber_4.sizePolicy().hasHeightForWidth())
        self.lcdNumber_4.setSizePolicy(sizePolicy)
        self.lcdNumber_4.setMinimumSize(QSize(50, 8))
        self.lcdNumber_4.setMaximumSize(QSize(60, 25))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber_4.setPalette(palette23)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setDigitCount(1)
        self.lcdNumber_4.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_4.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber_4)

        self.lcdNumber_5 = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber_5.sizePolicy().hasHeightForWidth())
        self.lcdNumber_5.setSizePolicy(sizePolicy)
        self.lcdNumber_5.setMinimumSize(QSize(50, 8))
        self.lcdNumber_5.setMaximumSize(QSize(60, 25))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette24.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber_5.setPalette(palette24)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setDigitCount(1)
        self.lcdNumber_5.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_5.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber_5)

        self.lcdNumber_6 = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber_6.sizePolicy().hasHeightForWidth())
        self.lcdNumber_6.setSizePolicy(sizePolicy)
        self.lcdNumber_6.setMinimumSize(QSize(50, 8))
        self.lcdNumber_6.setMaximumSize(QSize(60, 25))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette25.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette25.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber_6.setPalette(palette25)
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setDigitCount(1)
        self.lcdNumber_6.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_6.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber_6)

        self.lcdNumber_3 = QLCDNumber(self.verticalGroupBox_2)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lcdNumber_3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_3.setSizePolicy(sizePolicy)
        self.lcdNumber_3.setMinimumSize(QSize(50, 8))
        self.lcdNumber_3.setMaximumSize(QSize(60, 25))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush30)
        palette26.setBrush(QPalette.Active, QPalette.ButtonText, brush30)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush30)
        palette26.setBrush(QPalette.Inactive, QPalette.ButtonText, brush30)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        self.lcdNumber_3.setPalette(palette26)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setDigitCount(1)
        self.lcdNumber_3.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_3.setProperty("intValue", 0)

        self.verticalLayout_3.addWidget(self.lcdNumber_3)


        self.horizontalLayout_2.addWidget(self.verticalGroupBox_2)

        self.graphicsView = QGraphicsView(self.horizontalWidget1)
        self.graphicsView.setObjectName(u"graphicsView")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy3)
        self.graphicsView.setMinimumSize(QSize(250, 250))
        self.graphicsView.setMaximumSize(QSize(350, 600))
        palette27 = QPalette()
        brush31 = QBrush(QColor(186, 186, 186, 255))
        brush31.setStyle(Qt.SolidPattern)
        palette27.setBrush(QPalette.Active, QPalette.Base, brush31)
        palette27.setBrush(QPalette.Active, QPalette.Window, brush31)
        palette27.setBrush(QPalette.Inactive, QPalette.Base, brush31)
        palette27.setBrush(QPalette.Disabled, QPalette.Base, brush31)
        self.graphicsView.setPalette(palette27)
        self.graphicsView.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QFrame.Shape.Box)
        self.graphicsView.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView.setLineWidth(1)

        self.horizontalLayout_2.addWidget(self.graphicsView)

        self.verticalGroupBox_2.raise_()
        self.verticalGroupBox.raise_()
        self.graphicsView.raise_()

        self.gridLayout_2.addWidget(self.horizontalWidget1, 3, 0, 1, 1)

        self.label_2 = QLabel(self.gridWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(16777215, 40))
        palette28 = QPalette()
        brush32 = QBrush(QColor(200, 65, 20, 228))
        brush32.setStyle(Qt.SolidPattern)
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush32)
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush32)
        self.label_2.setPalette(palette28)
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setUnderline(True)
        font4.setKerning(True)
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)


        self.retranslateUi(LeafBotForm)

        QMetaObject.connectSlotsByName(LeafBotForm)
    # setupUi

    def retranslateUi(self, LeafBotForm):
        LeafBotForm.setWindowTitle(QCoreApplication.translate("LeafBotForm", u"LeafBot", None))
        self.pushButton_7.setText(QCoreApplication.translate("LeafBotForm", u"Detect Leaf", None))
        self.pushButton_11.setText(QCoreApplication.translate("LeafBotForm", u"Move Backward", None))
        self.pushButton_9.setText(QCoreApplication.translate("LeafBotForm", u"Move Forward", None))
        self.pushButton_8.setText(QCoreApplication.translate("LeafBotForm", u"Pick Leaf", None))
        self.pushButton_10.setText(QCoreApplication.translate("LeafBotForm", u"Segment Leaf", None))
        self.pushButton_12.setText(QCoreApplication.translate("LeafBotForm", u"Park to Plant", None))
        self.pushButton_3.setText(QCoreApplication.translate("LeafBotForm", u"Luanch All", None))
        self.LeafBotLogo.setText("")
        self.pushButton.setText(QCoreApplication.translate("LeafBotForm", u"Close All", None))
        self.pushButton_6.setText(QCoreApplication.translate("LeafBotForm", u"J2", None))
        self.pushButton_5.setText(QCoreApplication.translate("LeafBotForm", u"J1", None))
        self.pushButton_14.setText(QCoreApplication.translate("LeafBotForm", u"J3", None))
        self.pushButton_13.setText(QCoreApplication.translate("LeafBotForm", u"J4", None))
        self.pushButton_4.setText(QCoreApplication.translate("LeafBotForm", u"J5", None))
        self.pushButton_2.setText(QCoreApplication.translate("LeafBotForm", u"J6", None))
        self.label_2.setText(QCoreApplication.translate("LeafBotForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#a8ff06;\">LEAFBOT</span><span style=\" font-size:18pt; color:#ff0000;\"> CONSOLE</span></p></body></html>", None))
    # retranslateUi

