# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LeafBot.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QButtonGroup,
    QComboBox, QDoubleSpinBox, QFrame, QGraphicsView,
    QGridLayout, QLabel, QPushButton, QSizePolicy,
    QSpinBox, QVBoxLayout, QWidget)

class Ui_LeafBotForm(object):
    def setupUi(self, LeafBotForm):
        if not LeafBotForm.objectName():
            LeafBotForm.setObjectName(u"LeafBotForm")
        LeafBotForm.setWindowModality(Qt.WindowModality.WindowModal)
        LeafBotForm.resize(1000, 850)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LeafBotForm.sizePolicy().hasHeightForWidth())
        LeafBotForm.setSizePolicy(sizePolicy)
        LeafBotForm.setMaximumSize(QSize(1000, 1000))
        palette = QPalette()
        brush = QBrush(QColor(59, 129, 26, 228))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(85, 255, 0, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(118, 118, 118, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 228))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        brush4 = QBrush(QColor(29, 29, 29, 179))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(24, 20, 19, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush6 = QBrush(QColor(175, 175, 175, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        LeafBotForm.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        LeafBotForm.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"emblem-synchronized"))
        LeafBotForm.setWindowIcon(icon)
        LeafBotForm.setWindowOpacity(1.000000000000000)
        self.gridFrame = QFrame(LeafBotForm)
        self.gridFrame.setObjectName(u"gridFrame")
        self.gridFrame.setGeometry(QRect(10, 0, 900, 871))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy1)
        self.gridFrame.setMinimumSize(QSize(500, 0))
        palette1 = QPalette()
        brush7 = QBrush(QColor(36, 142, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush7)
        brush8 = QBrush(QColor(255, 255, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        brush9 = QBrush(QColor(83, 110, 230, 179))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        self.gridFrame.setPalette(palette1)
        self.verticalWidget = QWidget(self.gridFrame)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalWidget.setGeometry(QRect(180, 170, 550, 145))
        self.verticalWidget.setMinimumSize(QSize(550, 145))
        self.verticalWidget.setMaximumSize(QSize(550, 145))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.verticalWidget.setFont(font1)
        self.verticalLayout = QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widget = QWidget(self.verticalWidget)
        self.widget.setObjectName(u"widget")
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(0, 10))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setKerning(True)
        self.widget.setFont(font2)
        self.gridLayout = QGridLayout(self.widget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_detect_leaf = QPushButton(self.widget)
        self.pushButton_detect_leaf.setObjectName(u"pushButton_detect_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_detect_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_detect_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_detect_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_detect_leaf, 1, 1, 1, 1)

        self.pushButton_pick_leaf = QPushButton(self.widget)
        self.pushButton_pick_leaf.setObjectName(u"pushButton_pick_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_pick_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_pick_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_pick_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_pick_leaf, 1, 3, 1, 1)

        self.pushButton_segment_leaf = QPushButton(self.widget)
        self.pushButton_segment_leaf.setObjectName(u"pushButton_segment_leaf")
        sizePolicy1.setHeightForWidth(self.pushButton_segment_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_segment_leaf.setSizePolicy(sizePolicy1)
        self.pushButton_segment_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_segment_leaf, 1, 4, 1, 1)

        self.pushButton_close_all = QPushButton(self.widget)
        self.pushButton_close_all.setObjectName(u"pushButton_close_all")
        sizePolicy1.setHeightForWidth(self.pushButton_close_all.sizePolicy().hasHeightForWidth())
        self.pushButton_close_all.setSizePolicy(sizePolicy1)
        self.pushButton_close_all.setMinimumSize(QSize(120, 25))
        self.pushButton_close_all.setMaximumSize(QSize(120, 25))
        palette2 = QPalette()
        brush10 = QBrush(QColor(255, 85, 127, 228))
        brush10.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        brush11 = QBrush(QColor(165, 29, 45, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush10)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        self.pushButton_close_all.setPalette(palette2)
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        font3.setKerning(True)
        self.pushButton_close_all.setFont(font3)

        self.gridLayout.addWidget(self.pushButton_close_all, 0, 4, 1, 1)

        self.pushButton_luanch_all = QPushButton(self.widget)
        self.pushButton_luanch_all.setObjectName(u"pushButton_luanch_all")
        sizePolicy1.setHeightForWidth(self.pushButton_luanch_all.sizePolicy().hasHeightForWidth())
        self.pushButton_luanch_all.setSizePolicy(sizePolicy1)
        self.pushButton_luanch_all.setMinimumSize(QSize(120, 25))
        self.pushButton_luanch_all.setMaximumSize(QSize(120, 25))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        brush12 = QBrush(QColor(26, 95, 180, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush10)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.pushButton_luanch_all.setPalette(palette3)
        self.pushButton_luanch_all.setFont(font3)

        self.gridLayout.addWidget(self.pushButton_luanch_all, 0, 1, 1, 1)

        self.pushButton_show_origin = QPushButton(self.widget)
        self.pushButton_show_origin.setObjectName(u"pushButton_show_origin")
        sizePolicy1.setHeightForWidth(self.pushButton_show_origin.sizePolicy().hasHeightForWidth())
        self.pushButton_show_origin.setSizePolicy(sizePolicy1)
        self.pushButton_show_origin.setMinimumSize(QSize(120, 25))
        self.pushButton_show_origin.setMaximumSize(QSize(120, 25))
        palette4 = QPalette()
        brush13 = QBrush(QColor(0, 0, 127, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        self.pushButton_show_origin.setPalette(palette4)
        self.pushButton_show_origin.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_show_origin, 0, 3, 1, 1)

        self.pushButton_park_to_plant = QPushButton(self.widget)
        self.pushButton_park_to_plant.setObjectName(u"pushButton_park_to_plant")
        sizePolicy1.setHeightForWidth(self.pushButton_park_to_plant.sizePolicy().hasHeightForWidth())
        self.pushButton_park_to_plant.setSizePolicy(sizePolicy1)
        self.pushButton_park_to_plant.setMinimumSize(QSize(120, 25))
        self.pushButton_park_to_plant.setMaximumSize(QSize(120, 25))
        palette5 = QPalette()
        brush14 = QBrush(QColor(237, 51, 59, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush14)
        brush15 = QBrush(QColor(255, 255, 255, 228))
        brush15.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_park_to_plant.setPalette(palette5)
        self.pushButton_park_to_plant.setFont(font2)
        self.pushButton_park_to_plant.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_park_to_plant, 3, 3, 1, 1)


        self.verticalLayout.addWidget(self.widget, 0, Qt.AlignmentFlag.AlignHCenter)

        self.graphicsView = QGraphicsView(self.gridFrame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(391, 313, 500, 381))
        sizePolicy1.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy1)
        self.graphicsView.setMinimumSize(QSize(500, 250))
        self.graphicsView.setMaximumSize(QSize(500, 400))
        palette6 = QPalette()
        brush16 = QBrush(QColor(186, 186, 186, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush16)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush16)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush16)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush16)
        self.graphicsView.setPalette(palette6)
        self.graphicsView.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setFrameShape(QFrame.Shape.Box)
        self.graphicsView.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView.setLineWidth(1)
        self.graphicsView.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView.setInteractive(True)
        self.layoutWidget = QWidget(self.gridFrame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 305, 376, 478))
        self.layoutWidget.setMinimumSize(QSize(100, 0))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setUnderline(False)
        self.layoutWidget.setFont(font4)
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.pushButton_move_all = QPushButton(self.layoutWidget)
        self.pushButton_move_all.setObjectName(u"pushButton_move_all")
        sizePolicy1.setHeightForWidth(self.pushButton_move_all.sizePolicy().hasHeightForWidth())
        self.pushButton_move_all.setSizePolicy(sizePolicy1)
        self.pushButton_move_all.setMinimumSize(QSize(120, 30))
        palette7 = QPalette()
        brush17 = QBrush(QColor(170, 255, 255, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush17)
        brush18 = QBrush(QColor(0, 0, 0, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush17)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush17)
        self.pushButton_move_all.setPalette(palette7)
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(True)
        font5.setUnderline(False)
        self.pushButton_move_all.setFont(font5)

        self.gridLayout_3.addWidget(self.pushButton_move_all, 7, 1, 1, 1)

        self.pushButton_set_torque = QPushButton(self.layoutWidget)
        self.pushButton_set_torque.setObjectName(u"pushButton_set_torque")
        sizePolicy1.setHeightForWidth(self.pushButton_set_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_set_torque.setSizePolicy(sizePolicy1)
        self.pushButton_set_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_set_torque.setMaximumSize(QSize(120, 25))
        palette8 = QPalette()
        brush19 = QBrush(QColor(76, 76, 76, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_set_torque.setPalette(palette8)
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setKerning(True)
        self.pushButton_set_torque.setFont(font6)

        self.gridLayout_3.addWidget(self.pushButton_set_torque, 3, 2, 1, 1)

        self.spinBox_J6 = QSpinBox(self.layoutWidget)
        self.spinBox_J6.setObjectName(u"spinBox_J6")
        self.spinBox_J6.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J6.sizePolicy().hasHeightForWidth())
        self.spinBox_J6.setSizePolicy(sizePolicy1)
        self.spinBox_J6.setMinimumSize(QSize(120, 0))
        palette9 = QPalette()
        brush20 = QBrush(QColor(60, 255, 227, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        brush21 = QBrush(QColor(255, 255, 255, 179))
        brush21.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J6.setPalette(palette9)
        font7 = QFont()
        font7.setPointSize(12)
        font7.setWeight(QFont.ExtraBold)
        font7.setItalic(False)
        font7.setUnderline(False)
        font7.setKerning(True)
        self.spinBox_J6.setFont(font7)
        self.spinBox_J6.setAutoFillBackground(False)
        self.spinBox_J6.setWrapping(False)
        self.spinBox_J6.setFrame(True)
        self.spinBox_J6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J6.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J6.setMaximum(180)
        self.spinBox_J6.setValue(180)

        self.gridLayout_3.addWidget(self.spinBox_J6, 6, 1, 1, 1)

        self.spinBox_J3 = QSpinBox(self.layoutWidget)
        self.spinBox_J3.setObjectName(u"spinBox_J3")
        self.spinBox_J3.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J3.sizePolicy().hasHeightForWidth())
        self.spinBox_J3.setSizePolicy(sizePolicy1)
        self.spinBox_J3.setMinimumSize(QSize(120, 0))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J3.setPalette(palette10)
        self.spinBox_J3.setFont(font7)
        self.spinBox_J3.setAutoFillBackground(False)
        self.spinBox_J3.setWrapping(False)
        self.spinBox_J3.setFrame(True)
        self.spinBox_J3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J3.setMaximum(180)
        self.spinBox_J3.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J3, 3, 1, 1, 1)

        self.pushButton_J6 = QPushButton(self.layoutWidget)
        self.buttonGroup = QButtonGroup(LeafBotForm)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.pushButton_J6)
        self.pushButton_J6.setObjectName(u"pushButton_J6")
        self.pushButton_J6.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J6.sizePolicy().hasHeightForWidth())
        self.pushButton_J6.setSizePolicy(sizePolicy1)
        self.pushButton_J6.setMinimumSize(QSize(120, 0))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        brush22 = QBrush(QColor(254, 254, 254, 179))
        brush22.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush15)
        brush23 = QBrush(QColor(36, 31, 49, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J6.setPalette(palette11)
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(True)
        font8.setUnderline(False)
        self.pushButton_J6.setFont(font8)

        self.gridLayout_3.addWidget(self.pushButton_J6, 6, 0, 1, 1)

        self.pushButton_zero_position = QPushButton(self.layoutWidget)
        self.pushButton_zero_position.setObjectName(u"pushButton_zero_position")
        sizePolicy1.setHeightForWidth(self.pushButton_zero_position.sizePolicy().hasHeightForWidth())
        self.pushButton_zero_position.setSizePolicy(sizePolicy1)
        self.pushButton_zero_position.setMinimumSize(QSize(120, 25))
        self.pushButton_zero_position.setMaximumSize(QSize(120, 30))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_zero_position.setPalette(palette12)
        self.pushButton_zero_position.setFont(font6)
        self.pushButton_zero_position.setIconSize(QSize(30, 16))

        self.gridLayout_3.addWidget(self.pushButton_zero_position, 5, 2, 1, 1)

        self.pushButton_J2 = QPushButton(self.layoutWidget)
        self.buttonGroup.addButton(self.pushButton_J2)
        self.pushButton_J2.setObjectName(u"pushButton_J2")
        self.pushButton_J2.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J2.sizePolicy().hasHeightForWidth())
        self.pushButton_J2.setSizePolicy(sizePolicy1)
        self.pushButton_J2.setMinimumSize(QSize(120, 0))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush15)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J2.setPalette(palette13)
        self.pushButton_J2.setFont(font8)

        self.gridLayout_3.addWidget(self.pushButton_J2, 2, 0, 1, 1)

        self.pushButton_train_eye2hand = QPushButton(self.layoutWidget)
        self.pushButton_train_eye2hand.setObjectName(u"pushButton_train_eye2hand")
        sizePolicy1.setHeightForWidth(self.pushButton_train_eye2hand.sizePolicy().hasHeightForWidth())
        self.pushButton_train_eye2hand.setSizePolicy(sizePolicy1)
        self.pushButton_train_eye2hand.setMinimumSize(QSize(120, 25))
        self.pushButton_train_eye2hand.setMaximumSize(QSize(120, 25))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_train_eye2hand.setPalette(palette14)
        self.pushButton_train_eye2hand.setFont(font6)

        self.gridLayout_3.addWidget(self.pushButton_train_eye2hand, 6, 2, 1, 1)

        self.pushButton_off_torque = QPushButton(self.layoutWidget)
        self.pushButton_off_torque.setObjectName(u"pushButton_off_torque")
        sizePolicy1.setHeightForWidth(self.pushButton_off_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_off_torque.setSizePolicy(sizePolicy1)
        self.pushButton_off_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_off_torque.setMaximumSize(QSize(150, 25))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_off_torque.setPalette(palette15)
        self.pushButton_off_torque.setFont(font6)
        self.pushButton_off_torque.setIconSize(QSize(30, 16))

        self.gridLayout_3.addWidget(self.pushButton_off_torque, 4, 2, 1, 1)

        self.pushButton_Imitation = QPushButton(self.layoutWidget)
        self.pushButton_Imitation.setObjectName(u"pushButton_Imitation")
        sizePolicy1.setHeightForWidth(self.pushButton_Imitation.sizePolicy().hasHeightForWidth())
        self.pushButton_Imitation.setSizePolicy(sizePolicy1)
        self.pushButton_Imitation.setMinimumSize(QSize(120, 25))
        self.pushButton_Imitation.setMaximumSize(QSize(120, 25))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_Imitation.setPalette(palette16)
        self.pushButton_Imitation.setFont(font6)
        self.pushButton_Imitation.setIconSize(QSize(30, 16))

        self.gridLayout_3.addWidget(self.pushButton_Imitation, 1, 2, 1, 1)

        self.pushButton_read_servo = QPushButton(self.layoutWidget)
        self.pushButton_read_servo.setObjectName(u"pushButton_read_servo")
        sizePolicy1.setHeightForWidth(self.pushButton_read_servo.sizePolicy().hasHeightForWidth())
        self.pushButton_read_servo.setSizePolicy(sizePolicy1)
        self.pushButton_read_servo.setMinimumSize(QSize(120, 25))
        self.pushButton_read_servo.setMaximumSize(QSize(120, 25))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Button, brush19)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush19)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush19)
        self.pushButton_read_servo.setPalette(palette17)
        self.pushButton_read_servo.setFont(font6)

        self.gridLayout_3.addWidget(self.pushButton_read_servo, 2, 2, 1, 1)

        self.spinBox_J5 = QSpinBox(self.layoutWidget)
        self.spinBox_J5.setObjectName(u"spinBox_J5")
        self.spinBox_J5.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J5.sizePolicy().hasHeightForWidth())
        self.spinBox_J5.setSizePolicy(sizePolicy1)
        self.spinBox_J5.setMinimumSize(QSize(120, 0))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette18.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette18.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette18.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette18.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J5.setPalette(palette18)
        self.spinBox_J5.setFont(font7)
        self.spinBox_J5.setAutoFillBackground(False)
        self.spinBox_J5.setWrapping(False)
        self.spinBox_J5.setFrame(True)
        self.spinBox_J5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J5.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J5.setMaximum(180)
        self.spinBox_J5.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J5, 5, 1, 1, 1)

        self.pushButton_J3 = QPushButton(self.layoutWidget)
        self.buttonGroup.addButton(self.pushButton_J3)
        self.pushButton_J3.setObjectName(u"pushButton_J3")
        self.pushButton_J3.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J3.sizePolicy().hasHeightForWidth())
        self.pushButton_J3.setSizePolicy(sizePolicy1)
        self.pushButton_J3.setMinimumSize(QSize(120, 0))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush15)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J3.setPalette(palette19)
        self.pushButton_J3.setFont(font)
        self.pushButton_J3.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(192, 184, 160);\n"
"	        }\n"
"")

        self.gridLayout_3.addWidget(self.pushButton_J3, 3, 0, 1, 1)

        self.spinBox_J1 = QSpinBox(self.layoutWidget)
        self.spinBox_J1.setObjectName(u"spinBox_J1")
        self.spinBox_J1.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J1.sizePolicy().hasHeightForWidth())
        self.spinBox_J1.setSizePolicy(sizePolicy1)
        self.spinBox_J1.setMinimumSize(QSize(120, 0))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette20.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette20.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette20.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette20.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette20.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette20.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J1.setPalette(palette20)
        self.spinBox_J1.setFont(font7)
        self.spinBox_J1.setAutoFillBackground(False)
        self.spinBox_J1.setWrapping(False)
        self.spinBox_J1.setFrame(True)
        self.spinBox_J1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J1.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J1.setMaximum(180)
        self.spinBox_J1.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J1, 1, 1, 1, 1)

        self.pushButton_J1 = QPushButton(self.layoutWidget)
        self.buttonGroup.addButton(self.pushButton_J1)
        self.pushButton_J1.setObjectName(u"pushButton_J1")
        self.pushButton_J1.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J1.sizePolicy().hasHeightForWidth())
        self.pushButton_J1.setSizePolicy(sizePolicy1)
        self.pushButton_J1.setMinimumSize(QSize(120, 0))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush15)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J1.setPalette(palette21)
        self.pushButton_J1.setFont(font8)
        self.pushButton_J1.setAutoDefault(False)
        self.pushButton_J1.setFlat(False)

        self.gridLayout_3.addWidget(self.pushButton_J1, 1, 0, 1, 1)

        self.spinBox_J4 = QSpinBox(self.layoutWidget)
        self.spinBox_J4.setObjectName(u"spinBox_J4")
        self.spinBox_J4.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J4.sizePolicy().hasHeightForWidth())
        self.spinBox_J4.setSizePolicy(sizePolicy1)
        self.spinBox_J4.setMinimumSize(QSize(120, 0))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette22.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette22.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette22.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette22.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette22.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette22.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette22.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette22.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J4.setPalette(palette22)
        self.spinBox_J4.setFont(font7)
        self.spinBox_J4.setAutoFillBackground(False)
        self.spinBox_J4.setWrapping(False)
        self.spinBox_J4.setFrame(True)
        self.spinBox_J4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J4.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J4.setMaximum(180)
        self.spinBox_J4.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J4, 4, 1, 1, 1)

        self.spinBox_J2 = QSpinBox(self.layoutWidget)
        self.spinBox_J2.setObjectName(u"spinBox_J2")
        self.spinBox_J2.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_J2.sizePolicy().hasHeightForWidth())
        self.spinBox_J2.setSizePolicy(sizePolicy1)
        self.spinBox_J2.setMinimumSize(QSize(120, 0))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette23.setBrush(QPalette.Active, QPalette.Shadow, brush8)
        palette23.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush18)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette23.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette23.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush8)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Disabled, QPalette.Shadow, brush8)
        palette23.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        self.spinBox_J2.setPalette(palette23)
        self.spinBox_J2.setFont(font7)
        self.spinBox_J2.setAutoFillBackground(False)
        self.spinBox_J2.setWrapping(False)
        self.spinBox_J2.setFrame(True)
        self.spinBox_J2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J2.setMaximum(180)
        self.spinBox_J2.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J2, 2, 1, 1, 1)

        self.pushButton_J4 = QPushButton(self.layoutWidget)
        self.buttonGroup.addButton(self.pushButton_J4)
        self.pushButton_J4.setObjectName(u"pushButton_J4")
        self.pushButton_J4.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J4.sizePolicy().hasHeightForWidth())
        self.pushButton_J4.setSizePolicy(sizePolicy1)
        self.pushButton_J4.setMinimumSize(QSize(120, 0))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette24.setBrush(QPalette.Active, QPalette.Text, brush15)
        palette24.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette24.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette24.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J4.setPalette(palette24)
        self.pushButton_J4.setFont(font8)

        self.gridLayout_3.addWidget(self.pushButton_J4, 4, 0, 1, 1)

        self.pushButton_J5 = QPushButton(self.layoutWidget)
        self.buttonGroup.addButton(self.pushButton_J5)
        self.pushButton_J5.setObjectName(u"pushButton_J5")
        self.pushButton_J5.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_J5.sizePolicy().hasHeightForWidth())
        self.pushButton_J5.setSizePolicy(sizePolicy1)
        self.pushButton_J5.setMinimumSize(QSize(120, 0))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette25.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette25.setBrush(QPalette.Active, QPalette.Text, brush15)
        palette25.setBrush(QPalette.Active, QPalette.ButtonText, brush23)
        palette25.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette25.setBrush(QPalette.Inactive, QPalette.Text, brush15)
        palette25.setBrush(QPalette.Inactive, QPalette.ButtonText, brush23)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette25.setBrush(QPalette.Disabled, QPalette.Text, brush15)
        palette25.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.pushButton_J5.setPalette(palette25)
        self.pushButton_J5.setFont(font8)

        self.gridLayout_3.addWidget(self.pushButton_J5, 5, 0, 1, 1)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        palette26 = QPalette()
        brush24 = QBrush(QColor(255, 147, 147, 228))
        brush24.setStyle(Qt.SolidPattern)
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush24)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush24)
        self.label_5.setPalette(palette26)

        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.spinBox_2 = QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setMinimumSize(QSize(100, 0))
        palette27 = QPalette()
        brush25 = QBrush(QColor(54, 35, 115, 228))
        brush25.setStyle(Qt.SolidPattern)
        palette27.setBrush(QPalette.Active, QPalette.Text, brush25)
        palette27.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette27.setBrush(QPalette.Inactive, QPalette.Text, brush25)
        palette27.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        self.spinBox_2.setPalette(palette27)
        self.spinBox_2.setFont(font4)
        self.spinBox_2.setWrapping(False)
        self.spinBox_2.setFrame(False)
        self.spinBox_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_2.setAccelerated(False)
        self.spinBox_2.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setSuffix(u"")
        self.spinBox_2.setPrefix(u"")
        self.spinBox_2.setMinimum(-180)
        self.spinBox_2.setMaximum(180)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.gridLayout_4.addWidget(self.spinBox_2, 1, 1, 1, 1)

        self.spinBox_3 = QSpinBox(self.layoutWidget)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setMinimumSize(QSize(100, 0))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.Text, brush25)
        palette28.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette28.setBrush(QPalette.Inactive, QPalette.Text, brush25)
        palette28.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        self.spinBox_3.setPalette(palette28)
        self.spinBox_3.setFont(font4)
        self.spinBox_3.setWrapping(False)
        self.spinBox_3.setFrame(False)
        self.spinBox_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_3.setAccelerated(False)
        self.spinBox_3.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setSuffix(u"")
        self.spinBox_3.setPrefix(u"")
        self.spinBox_3.setMinimum(-180)
        self.spinBox_3.setMaximum(180)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.gridLayout_4.addWidget(self.spinBox_3, 2, 1, 1, 1)

        self.spinBox = QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimumSize(QSize(100, 0))
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.Text, brush25)
        palette29.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette29.setBrush(QPalette.Inactive, QPalette.Text, brush25)
        palette29.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        self.spinBox.setPalette(palette29)
        self.spinBox.setFont(font4)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(False)
        self.spinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox.setAccelerated(False)
        self.spinBox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setSuffix(u"")
        self.spinBox.setPrefix(u"")
        self.spinBox.setMinimum(-180)
        self.spinBox.setMaximum(180)
        self.spinBox.setSingleStep(10)
        self.spinBox.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.gridLayout_4.addWidget(self.spinBox, 0, 1, 1, 1)

        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")
        palette30 = QPalette()
        brush26 = QBrush(QColor(249, 242, 38, 228))
        brush26.setStyle(Qt.SolidPattern)
        palette30.setBrush(QPalette.Active, QPalette.WindowText, brush26)
        palette30.setBrush(QPalette.Inactive, QPalette.WindowText, brush26)
        self.label_7.setPalette(palette30)

        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)

        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")
        palette31 = QPalette()
        palette31.setBrush(QPalette.Active, QPalette.WindowText, brush26)
        palette31.setBrush(QPalette.Inactive, QPalette.WindowText, brush26)
        self.label_8.setPalette(palette31)

        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)

        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setObjectName(u"label_9")
        palette32 = QPalette()
        palette32.setBrush(QPalette.Active, QPalette.WindowText, brush26)
        palette32.setBrush(QPalette.Inactive, QPalette.WindowText, brush26)
        self.label_9.setPalette(palette32)

        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_4, 7, 0, 1, 1)


        self.verticalLayout_2.addLayout(self.gridLayout_3)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 25))
        palette33 = QPalette()
        palette33.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette33.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette33.setBrush(QPalette.Disabled, QPalette.WindowText, brush15)
        self.label_3.setPalette(palette33)
        self.label_3.setFont(font4)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)

        self.pushButton_move_backward = QPushButton(self.layoutWidget)
        self.pushButton_move_backward.setObjectName(u"pushButton_move_backward")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward.setMaximumSize(QSize(120, 25))
        palette34 = QPalette()
        palette34.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette34.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette34.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette34.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_backward.setPalette(palette34)
        self.pushButton_move_backward.setFont(font6)
        self.pushButton_move_backward.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_backward, 4, 2, 1, 1)

        self.pushButton_move_backward_5 = QPushButton(self.layoutWidget)
        self.pushButton_move_backward_5.setObjectName(u"pushButton_move_backward_5")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward_5.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward_5.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward_5.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward_5.setMaximumSize(QSize(120, 25))
        palette35 = QPalette()
        palette35.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette35.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette35.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette35.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_backward_5.setPalette(palette35)
        self.pushButton_move_backward_5.setFont(font6)
        self.pushButton_move_backward_5.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_backward_5, 5, 1, 1, 1)

        self.pushButton_move_backward_4 = QPushButton(self.layoutWidget)
        self.pushButton_move_backward_4.setObjectName(u"pushButton_move_backward_4")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward_4.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward_4.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward_4.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward_4.setMaximumSize(QSize(120, 25))
        palette36 = QPalette()
        palette36.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette36.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette36.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette36.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_backward_4.setPalette(palette36)
        self.pushButton_move_backward_4.setFont(font6)
        self.pushButton_move_backward_4.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_backward_4, 4, 1, 1, 1)

        self.doubleSpinBox_3 = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        sizePolicy1.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy1)
        self.doubleSpinBox_3.setMinimumSize(QSize(120, 25))
        palette37 = QPalette()
        palette37.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette37.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        self.doubleSpinBox_3.setPalette(palette37)
        self.doubleSpinBox_3.setFont(font4)

        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 3, 0, 1, 1)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(16777215, 25))
        palette38 = QPalette()
        palette38.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette38.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette38.setBrush(QPalette.Disabled, QPalette.WindowText, brush15)
        self.label.setPalette(palette38)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)

        self.comboBox_car_speed = QComboBox(self.layoutWidget)
        self.comboBox_car_speed.addItem("")
        self.comboBox_car_speed.addItem("")
        self.comboBox_car_speed.addItem("")
        self.comboBox_car_speed.setObjectName(u"comboBox_car_speed")
        palette39 = QPalette()
        palette39.setBrush(QPalette.Active, QPalette.ButtonText, brush18)
        palette39.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette39.setBrush(QPalette.Inactive, QPalette.ButtonText, brush15)
        palette39.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette39.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette39.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        self.comboBox_car_speed.setPalette(palette39)
        self.comboBox_car_speed.setFont(font4)

        self.gridLayout_2.addWidget(self.comboBox_car_speed, 3, 1, 1, 1)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        palette40 = QPalette()
        palette40.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette40.setBrush(QPalette.Disabled, QPalette.WindowText, brush15)
        self.label_4.setPalette(palette40)
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_4, 2, 1, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.pushButton_move_backward_2 = QPushButton(self.layoutWidget)
        self.pushButton_move_backward_2.setObjectName(u"pushButton_move_backward_2")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward_2.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward_2.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward_2.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward_2.setMaximumSize(QSize(120, 25))
        palette41 = QPalette()
        palette41.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette41.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette41.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette41.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_backward_2.setPalette(palette41)
        self.pushButton_move_backward_2.setFont(font6)
        self.pushButton_move_backward_2.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_backward_2, 5, 0, 1, 1)

        self.pushButton_move_backward_3 = QPushButton(self.layoutWidget)
        self.pushButton_move_backward_3.setObjectName(u"pushButton_move_backward_3")
        sizePolicy1.setHeightForWidth(self.pushButton_move_backward_3.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward_3.setSizePolicy(sizePolicy1)
        self.pushButton_move_backward_3.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward_3.setMaximumSize(QSize(120, 25))
        palette42 = QPalette()
        palette42.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette42.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette42.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette42.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_backward_3.setPalette(palette42)
        self.pushButton_move_backward_3.setFont(font6)
        self.pushButton_move_backward_3.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_backward_3, 5, 2, 1, 1)

        self.pushButton_move_forward = QPushButton(self.layoutWidget)
        self.pushButton_move_forward.setObjectName(u"pushButton_move_forward")
        sizePolicy1.setHeightForWidth(self.pushButton_move_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_forward.setSizePolicy(sizePolicy1)
        self.pushButton_move_forward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_forward.setMaximumSize(QSize(120, 25))
        palette43 = QPalette()
        palette43.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette43.setBrush(QPalette.Active, QPalette.ButtonText, brush15)
        palette43.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette43.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        self.pushButton_move_forward.setPalette(palette43)
        self.pushButton_move_forward.setFont(font6)
        self.pushButton_move_forward.setIconSize(QSize(30, 16))

        self.gridLayout_2.addWidget(self.pushButton_move_forward, 4, 0, 1, 1)

        self.doubleSpinBox_2 = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        sizePolicy1.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy1)
        self.doubleSpinBox_2.setMinimumSize(QSize(120, 25))
        palette44 = QPalette()
        palette44.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette44.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        self.doubleSpinBox_2.setPalette(palette44)
        font9 = QFont()
        font9.setPointSize(10)
        font9.setBold(True)
        font9.setUnderline(False)
        font9.setStyleStrategy(QFont.PreferDefault)
        self.doubleSpinBox_2.setFont(font9)

        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 3, 2, 1, 1)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        palette45 = QPalette()
        palette45.setBrush(QPalette.Active, QPalette.WindowText, brush24)
        palette45.setBrush(QPalette.Inactive, QPalette.WindowText, brush24)
        self.label_6.setPalette(palette45)
        self.label_6.setFont(font8)

        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 3, Qt.AlignmentFlag.AlignHCenter)


        self.verticalLayout_2.addLayout(self.gridLayout_2)

        self.LeafBotLogo = QLabel(self.gridFrame)
        self.LeafBotLogo.setObjectName(u"LeafBotLogo")
        self.LeafBotLogo.setEnabled(True)
        self.LeafBotLogo.setGeometry(QRect(390, 70, 100, 100))
        sizePolicy1.setHeightForWidth(self.LeafBotLogo.sizePolicy().hasHeightForWidth())
        self.LeafBotLogo.setSizePolicy(sizePolicy1)
        self.LeafBotLogo.setMinimumSize(QSize(100, 100))
        self.LeafBotLogo.setMaximumSize(QSize(100, 100))
        palette46 = QPalette()
        palette46.setBrush(QPalette.Active, QPalette.Window, brush8)
        self.LeafBotLogo.setPalette(palette46)
        font10 = QFont()
        font10.setPointSize(12)
        font10.setBold(True)
        font10.setHintingPreference(QFont.PreferFullHinting)
        self.LeafBotLogo.setFont(font10)
        self.LeafBotLogo.setTextFormat(Qt.TextFormat.PlainText)
        self.LeafBotLogo.setPixmap(QPixmap(u"../logo.jpg"))
        self.LeafBotLogo.setScaledContents(True)
        self.LeafBotLogo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.gridFrame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 30, 233, 31))
        self.label_2.setMaximumSize(QSize(16777215, 40))
        palette47 = QPalette()
        brush27 = QBrush(QColor(200, 65, 20, 228))
        brush27.setStyle(Qt.SolidPattern)
        palette47.setBrush(QPalette.Active, QPalette.WindowText, brush27)
        palette47.setBrush(QPalette.Inactive, QPalette.WindowText, brush27)
        self.label_2.setPalette(palette47)
        font11 = QFont()
        font11.setPointSize(12)
        font11.setBold(True)
        font11.setUnderline(True)
        font11.setKerning(True)
        self.label_2.setFont(font11)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.retranslateUi(LeafBotForm)
        self.pushButton_close_all.clicked.connect(self.verticalWidget.close)

        self.pushButton_J1.setDefault(False)


        QMetaObject.connectSlotsByName(LeafBotForm)
    # setupUi

    def retranslateUi(self, LeafBotForm):
        LeafBotForm.setWindowTitle(QCoreApplication.translate("LeafBotForm", u"LeafBot", None))
        self.pushButton_detect_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Detect Leaf", None))
        self.pushButton_pick_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Pick Leaf", None))
        self.pushButton_segment_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Segment Leaf", None))
        self.pushButton_close_all.setText(QCoreApplication.translate("LeafBotForm", u"Close All", None))
        self.pushButton_luanch_all.setText(QCoreApplication.translate("LeafBotForm", u"Luanch All", None))
        self.pushButton_show_origin.setText(QCoreApplication.translate("LeafBotForm", u"Show Origin", None))
        self.pushButton_park_to_plant.setText(QCoreApplication.translate("LeafBotForm", u"Park to Plant", None))
        self.pushButton_move_all.setText(QCoreApplication.translate("LeafBotForm", u"Move All", None))
        self.pushButton_set_torque.setText(QCoreApplication.translate("LeafBotForm", u"Set Torque", None))
        self.pushButton_J6.setText(QCoreApplication.translate("LeafBotForm", u"J6", None))
        self.pushButton_zero_position.setText(QCoreApplication.translate("LeafBotForm", u"Zero Position", None))
        self.pushButton_J2.setText(QCoreApplication.translate("LeafBotForm", u"J2", None))
        self.pushButton_train_eye2hand.setText(QCoreApplication.translate("LeafBotForm", u"Train Eye2Hand", None))
        self.pushButton_off_torque.setText(QCoreApplication.translate("LeafBotForm", u"Off Torque", None))
        self.pushButton_Imitation.setText(QCoreApplication.translate("LeafBotForm", u"Imitation", None))
        self.pushButton_read_servo.setText(QCoreApplication.translate("LeafBotForm", u"Read Servo", None))
        self.pushButton_J3.setText(QCoreApplication.translate("LeafBotForm", u"J3", None))
        self.pushButton_J1.setText(QCoreApplication.translate("LeafBotForm", u"J1", None))
        self.pushButton_J4.setText(QCoreApplication.translate("LeafBotForm", u"J4", None))
        self.pushButton_J5.setText(QCoreApplication.translate("LeafBotForm", u"J5", None))
        self.label_5.setText(QCoreApplication.translate("LeafBotForm", u"Arm", None))
        self.spinBox_2.setSpecialValueText("")
        self.spinBox_3.setSpecialValueText("")
        self.spinBox.setSpecialValueText("")
        self.label_7.setText(QCoreApplication.translate("LeafBotForm", u"R", None))
        self.label_8.setText(QCoreApplication.translate("LeafBotForm", u"P", None))
        self.label_9.setText(QCoreApplication.translate("LeafBotForm", u"Y", None))
        self.label_3.setText(QCoreApplication.translate("LeafBotForm", u"Right speed", None))
        self.pushButton_move_backward.setText(QCoreApplication.translate("LeafBotForm", u"Move Backward", None))
        self.pushButton_move_backward_5.setText(QCoreApplication.translate("LeafBotForm", u"Deccelerate", None))
        self.pushButton_move_backward_4.setText(QCoreApplication.translate("LeafBotForm", u"Accelerate", None))
        self.label.setText(QCoreApplication.translate("LeafBotForm", u"Left speed", None))
        self.comboBox_car_speed.setItemText(0, QCoreApplication.translate("LeafBotForm", u"1", None))
        self.comboBox_car_speed.setItemText(1, QCoreApplication.translate("LeafBotForm", u"2", None))
        self.comboBox_car_speed.setItemText(2, QCoreApplication.translate("LeafBotForm", u"3", None))

        self.label_4.setText(QCoreApplication.translate("LeafBotForm", u"Speed", None))
        self.pushButton_move_backward_2.setText(QCoreApplication.translate("LeafBotForm", u"Turn Left", None))
        self.pushButton_move_backward_3.setText(QCoreApplication.translate("LeafBotForm", u"Turn Right", None))
        self.pushButton_move_forward.setText(QCoreApplication.translate("LeafBotForm", u"Move Forward", None))
        self.label_6.setText(QCoreApplication.translate("LeafBotForm", u"Car", None))
        self.LeafBotLogo.setText("")
        self.label_2.setText(QCoreApplication.translate("LeafBotForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#248e00;\">LEAFBOT </span><span style=\" font-size:18pt; color:#ff0000;\">CONSOLE</span></p></body></html>", None))
    # retranslateUi

