# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LeafBot.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QButtonGroup,
    QFrame, QGraphicsView, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QPushButton, QSizePolicy,
    QSpacerItem, QSpinBox, QToolButton, QVBoxLayout,
    QWidget)

class Ui_LeafBotForm(object):
    def setupUi(self, LeafBotForm):
        if not LeafBotForm.objectName():
            LeafBotForm.setObjectName(u"LeafBotForm")
        LeafBotForm.setWindowModality(Qt.WindowModality.WindowModal)
        LeafBotForm.resize(900, 850)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LeafBotForm.sizePolicy().hasHeightForWidth())
        LeafBotForm.setSizePolicy(sizePolicy)
        LeafBotForm.setMaximumSize(QSize(1000, 1000))
        palette = QPalette()
        brush = QBrush(QColor(59, 129, 26, 228))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(85, 255, 0, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(118, 118, 118, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 228))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        brush4 = QBrush(QColor(29, 29, 29, 179))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(68, 57, 55, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush6 = QBrush(QColor(175, 175, 175, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush7 = QBrush(QColor(108, 90, 88, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        brush8 = QBrush(QColor(43, 36, 35, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        brush9 = QBrush(QColor(143, 120, 117, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        LeafBotForm.setPalette(palette)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        LeafBotForm.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"emblem-synchronized"))
        LeafBotForm.setWindowIcon(icon)
        LeafBotForm.setWindowOpacity(1.000000000000000)
        self.widget = QWidget(LeafBotForm)
        self.widget.setObjectName(u"widget")
        self.widget.setEnabled(True)
        self.widget.setGeometry(QRect(50, 20, 2000, 700))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(0, 0))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        brush10 = QBrush(QColor(134, 189, 93, 179))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        brush11 = QBrush(QColor(131, 131, 131, 179))
        brush11.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        brush12 = QBrush(QColor(99, 118, 106, 179))
        brush12.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        self.widget.setPalette(palette1)
        self.gridWidget = QWidget(self.widget)
        self.gridWidget.setObjectName(u"gridWidget")
        self.gridWidget.setGeometry(QRect(40, 20, 700, 850))
        self.gridWidget.setMinimumSize(QSize(500, 0))
        palette2 = QPalette()
        brush13 = QBrush(QColor(36, 142, 0, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush13)
        brush14 = QBrush(QColor(255, 255, 255, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        brush15 = QBrush(QColor(83, 110, 230, 179))
        brush15.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush15)
        self.gridWidget.setPalette(palette2)
        self.gridLayout_2 = QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.horizontalWidget = QWidget(self.gridWidget)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        self.horizontalWidget.setMinimumSize(QSize(500, 102))
        self.horizontalWidget.setMaximumSize(QSize(500, 102))
        self.horizontalLayout = QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.pushButton_3 = QPushButton(self.horizontalWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy2)
        self.pushButton_3.setMinimumSize(QSize(120, 25))
        self.pushButton_3.setMaximumSize(QSize(120, 25))
        palette3 = QPalette()
        brush16 = QBrush(QColor(255, 85, 127, 228))
        brush16.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        brush17 = QBrush(QColor(26, 95, 180, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush17)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush17)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush17)
        self.pushButton_3.setPalette(palette3)
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(True)
        font1.setKerning(True)
        self.pushButton_3.setFont(font1)

        self.horizontalLayout.addWidget(self.pushButton_3)

        self.LeafBotLogo = QLabel(self.horizontalWidget)
        self.LeafBotLogo.setObjectName(u"LeafBotLogo")
        self.LeafBotLogo.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.LeafBotLogo.sizePolicy().hasHeightForWidth())
        self.LeafBotLogo.setSizePolicy(sizePolicy2)
        self.LeafBotLogo.setMinimumSize(QSize(100, 100))
        self.LeafBotLogo.setMaximumSize(QSize(100, 100))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Window, brush14)
        self.LeafBotLogo.setPalette(palette4)
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setHintingPreference(QFont.PreferFullHinting)
        self.LeafBotLogo.setFont(font2)
        self.LeafBotLogo.setTextFormat(Qt.TextFormat.PlainText)
        self.LeafBotLogo.setPixmap(QPixmap(u"../logo.jpg"))
        self.LeafBotLogo.setScaledContents(True)
        self.LeafBotLogo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.LeafBotLogo)

        self.pushButton_21 = QPushButton(self.horizontalWidget)
        self.pushButton_21.setObjectName(u"pushButton_21")
        sizePolicy2.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy2)
        self.pushButton_21.setMinimumSize(QSize(120, 25))
        self.pushButton_21.setMaximumSize(QSize(120, 25))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        brush18 = QBrush(QColor(165, 29, 45, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush18)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush18)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush18)
        self.pushButton_21.setPalette(palette5)
        self.pushButton_21.setFont(font1)

        self.horizontalLayout.addWidget(self.pushButton_21)


        self.gridLayout_2.addWidget(self.horizontalWidget, 1, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.label_2 = QLabel(self.gridWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(16777215, 40))
        palette6 = QPalette()
        brush19 = QBrush(QColor(200, 65, 20, 228))
        brush19.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush19)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush19)
        self.label_2.setPalette(palette6)
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setUnderline(True)
        font3.setKerning(True)
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 50, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 0, 1, 1)

        self.verticalWidget = QWidget(self.gridWidget)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalWidget.setMinimumSize(QSize(550, 145))
        self.verticalWidget.setMaximumSize(QSize(550, 145))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        self.verticalWidget.setFont(font4)
        self.verticalLayout = QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widget1 = QWidget(self.verticalWidget)
        self.widget1.setObjectName(u"widget1")
        sizePolicy2.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy2)
        self.widget1.setMinimumSize(QSize(0, 10))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setKerning(True)
        self.widget1.setFont(font5)
        self.gridLayout = QGridLayout(self.widget1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_move_forward = QPushButton(self.widget1)
        self.pushButton_move_forward.setObjectName(u"pushButton_move_forward")
        sizePolicy2.setHeightForWidth(self.pushButton_move_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_forward.setSizePolicy(sizePolicy2)
        self.pushButton_move_forward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_forward.setMaximumSize(QSize(120, 25))
        palette7 = QPalette()
        brush20 = QBrush(QColor(237, 51, 59, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush20)
        brush21 = QBrush(QColor(255, 255, 255, 228))
        brush21.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush21)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        self.pushButton_move_forward.setPalette(palette7)
        self.pushButton_move_forward.setFont(font5)
        self.pushButton_move_forward.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_move_forward, 2, 3, 1, 1)

        self.pushButton_set_torque = QPushButton(self.widget1)
        self.pushButton_set_torque.setObjectName(u"pushButton_set_torque")
        sizePolicy2.setHeightForWidth(self.pushButton_set_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_set_torque.setSizePolicy(sizePolicy2)
        self.pushButton_set_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_set_torque.setMaximumSize(QSize(120, 25))
        palette8 = QPalette()
        brush22 = QBrush(QColor(119, 118, 123, 255))
        brush22.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_set_torque.setPalette(palette8)
        self.pushButton_set_torque.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_set_torque, 3, 1, 1, 1)

        self.pushButton_read_servo = QPushButton(self.widget1)
        self.pushButton_read_servo.setObjectName(u"pushButton_read_servo")
        sizePolicy2.setHeightForWidth(self.pushButton_read_servo.sizePolicy().hasHeightForWidth())
        self.pushButton_read_servo.setSizePolicy(sizePolicy2)
        self.pushButton_read_servo.setMinimumSize(QSize(120, 25))
        self.pushButton_read_servo.setMaximumSize(QSize(120, 25))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_read_servo.setPalette(palette9)
        self.pushButton_read_servo.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_read_servo, 0, 1, 1, 1)

        self.pushButton_park_to_plant = QPushButton(self.widget1)
        self.pushButton_park_to_plant.setObjectName(u"pushButton_park_to_plant")
        sizePolicy2.setHeightForWidth(self.pushButton_park_to_plant.sizePolicy().hasHeightForWidth())
        self.pushButton_park_to_plant.setSizePolicy(sizePolicy2)
        self.pushButton_park_to_plant.setMinimumSize(QSize(120, 25))
        self.pushButton_park_to_plant.setMaximumSize(QSize(120, 25))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush21)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        self.pushButton_park_to_plant.setPalette(palette10)
        self.pushButton_park_to_plant.setFont(font5)
        self.pushButton_park_to_plant.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_park_to_plant, 0, 3, 1, 1)

        self.pushButton_off_torque = QPushButton(self.widget1)
        self.pushButton_off_torque.setObjectName(u"pushButton_off_torque")
        sizePolicy2.setHeightForWidth(self.pushButton_off_torque.sizePolicy().hasHeightForWidth())
        self.pushButton_off_torque.setSizePolicy(sizePolicy2)
        self.pushButton_off_torque.setMinimumSize(QSize(120, 25))
        self.pushButton_off_torque.setMaximumSize(QSize(150, 25))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_off_torque.setPalette(palette11)
        self.pushButton_off_torque.setFont(font5)
        self.pushButton_off_torque.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_off_torque, 3, 2, 1, 1)

        self.pushButton_pick_leaf = QPushButton(self.widget1)
        self.pushButton_pick_leaf.setObjectName(u"pushButton_pick_leaf")
        sizePolicy2.setHeightForWidth(self.pushButton_pick_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_pick_leaf.setSizePolicy(sizePolicy2)
        self.pushButton_pick_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_pick_leaf.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_pick_leaf, 2, 0, 1, 1)

        self.pushButton_detect_leaf = QPushButton(self.widget1)
        self.pushButton_detect_leaf.setObjectName(u"pushButton_detect_leaf")
        sizePolicy2.setHeightForWidth(self.pushButton_detect_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_detect_leaf.setSizePolicy(sizePolicy2)
        self.pushButton_detect_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_detect_leaf.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_detect_leaf, 0, 0, 1, 1)

        self.pushButton_train_eye2hand = QPushButton(self.widget1)
        self.pushButton_train_eye2hand.setObjectName(u"pushButton_train_eye2hand")
        sizePolicy2.setHeightForWidth(self.pushButton_train_eye2hand.sizePolicy().hasHeightForWidth())
        self.pushButton_train_eye2hand.setSizePolicy(sizePolicy2)
        self.pushButton_train_eye2hand.setMinimumSize(QSize(120, 25))
        self.pushButton_train_eye2hand.setMaximumSize(QSize(120, 25))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_train_eye2hand.setPalette(palette12)
        self.pushButton_train_eye2hand.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_train_eye2hand, 2, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.pushButton_move_backward = QPushButton(self.widget1)
        self.pushButton_move_backward.setObjectName(u"pushButton_move_backward")
        sizePolicy2.setHeightForWidth(self.pushButton_move_backward.sizePolicy().hasHeightForWidth())
        self.pushButton_move_backward.setSizePolicy(sizePolicy2)
        self.pushButton_move_backward.setMinimumSize(QSize(120, 25))
        self.pushButton_move_backward.setMaximumSize(QSize(120, 25))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush21)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        self.pushButton_move_backward.setPalette(palette13)
        self.pushButton_move_backward.setFont(font5)
        self.pushButton_move_backward.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_move_backward, 3, 3, 1, 1)

        self.pushButton_segment_leaf = QPushButton(self.widget1)
        self.pushButton_segment_leaf.setObjectName(u"pushButton_segment_leaf")
        sizePolicy2.setHeightForWidth(self.pushButton_segment_leaf.sizePolicy().hasHeightForWidth())
        self.pushButton_segment_leaf.setSizePolicy(sizePolicy2)
        self.pushButton_segment_leaf.setMinimumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setMaximumSize(QSize(120, 25))
        self.pushButton_segment_leaf.setFont(font5)

        self.gridLayout.addWidget(self.pushButton_segment_leaf, 3, 0, 1, 1)

        self.pushButton_zero_position = QPushButton(self.widget1)
        self.pushButton_zero_position.setObjectName(u"pushButton_zero_position")
        sizePolicy2.setHeightForWidth(self.pushButton_zero_position.sizePolicy().hasHeightForWidth())
        self.pushButton_zero_position.setSizePolicy(sizePolicy2)
        self.pushButton_zero_position.setMinimumSize(QSize(120, 25))
        self.pushButton_zero_position.setMaximumSize(QSize(120, 30))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_zero_position.setPalette(palette14)
        self.pushButton_zero_position.setFont(font5)
        self.pushButton_zero_position.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_zero_position, 0, 2, 1, 1)

        self.pushButton_Imitation = QPushButton(self.widget1)
        self.pushButton_Imitation.setObjectName(u"pushButton_Imitation")
        sizePolicy2.setHeightForWidth(self.pushButton_Imitation.sizePolicy().hasHeightForWidth())
        self.pushButton_Imitation.setSizePolicy(sizePolicy2)
        self.pushButton_Imitation.setMinimumSize(QSize(120, 25))
        self.pushButton_Imitation.setMaximumSize(QSize(120, 25))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush14)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        self.pushButton_Imitation.setPalette(palette15)
        self.pushButton_Imitation.setFont(font5)
        self.pushButton_Imitation.setIconSize(QSize(30, 16))

        self.gridLayout.addWidget(self.pushButton_Imitation, 2, 2, 1, 1)


        self.verticalLayout.addWidget(self.widget1)

        self.toolButton = QToolButton(self.verticalWidget)
        self.toolButton.setObjectName(u"toolButton")
        palette16 = QPalette()
        brush23 = QBrush(QColor(85, 85, 255, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush23)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush23)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush23)
        self.toolButton.setPalette(palette16)
        self.toolButton.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)

        self.verticalLayout.addWidget(self.toolButton, 0, Qt.AlignmentFlag.AlignHCenter)


        self.gridLayout_2.addWidget(self.verticalWidget, 3, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalWidget_2 = QWidget(self.gridWidget)
        self.horizontalWidget_2.setObjectName(u"horizontalWidget_2")
        sizePolicy2.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy2)
        self.horizontalWidget_2.setMinimumSize(QSize(0, 600))
        self.horizontalWidget_2.setMaximumSize(QSize(600, 1200))
        palette17 = QPalette()
        brush24 = QBrush(QColor(255, 255, 255, 179))
        brush24.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush24)
        brush25 = QBrush(QColor(173, 171, 168, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.AlternateBase, brush25)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush24)
        palette17.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush25)
        palette17.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush25)
        self.horizontalWidget_2.setPalette(palette17)
        self.gridWidget1 = QWidget(self.horizontalWidget_2)
        self.gridWidget1.setObjectName(u"gridWidget1")
        self.gridWidget1.setGeometry(QRect(20, 40, 183, 242))
        self.gridWidget1.setMaximumSize(QSize(183, 242))
        self.gridLayout_3 = QGridLayout(self.gridWidget1)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.pushButton_J2 = QPushButton(self.gridWidget1)
        self.buttonGroup = QButtonGroup(LeafBotForm)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.pushButton_J2)
        self.pushButton_J2.setObjectName(u"pushButton_J2")
        self.pushButton_J2.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J2.sizePolicy().hasHeightForWidth())
        self.pushButton_J2.setSizePolicy(sizePolicy2)
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        brush26 = QBrush(QColor(254, 254, 254, 179))
        brush26.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush21)
        brush27 = QBrush(QColor(36, 31, 49, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J2.setPalette(palette18)
        self.pushButton_J2.setFont(font)

        self.gridLayout_3.addWidget(self.pushButton_J2, 1, 0, 1, 1)

        self.pushButton_J1 = QPushButton(self.gridWidget1)
        self.buttonGroup.addButton(self.pushButton_J1)
        self.pushButton_J1.setObjectName(u"pushButton_J1")
        self.pushButton_J1.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J1.sizePolicy().hasHeightForWidth())
        self.pushButton_J1.setSizePolicy(sizePolicy2)
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush21)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J1.setPalette(palette19)
        self.pushButton_J1.setFont(font)
        self.pushButton_J1.setAutoDefault(False)
        self.pushButton_J1.setFlat(False)

        self.gridLayout_3.addWidget(self.pushButton_J1, 0, 0, 1, 1)

        self.spinBox_J2 = QSpinBox(self.gridWidget1)
        self.spinBox_J2.setObjectName(u"spinBox_J2")
        self.spinBox_J2.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J2.sizePolicy().hasHeightForWidth())
        self.spinBox_J2.setSizePolicy(sizePolicy2)
        self.spinBox_J2.setMinimumSize(QSize(90, 0))
        palette20 = QPalette()
        brush28 = QBrush(QColor(60, 255, 227, 255))
        brush28.setStyle(Qt.SolidPattern)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush28)
        brush29 = QBrush(QColor(0, 0, 0, 255))
        brush29.setStyle(Qt.SolidPattern)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette20.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette20.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette20.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette20.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette20.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette20.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J2.setPalette(palette20)
        font6 = QFont()
        font6.setPointSize(12)
        font6.setWeight(QFont.ExtraBold)
        font6.setItalic(False)
        font6.setUnderline(False)
        font6.setKerning(True)
        self.spinBox_J2.setFont(font6)
        self.spinBox_J2.setAutoFillBackground(False)
        self.spinBox_J2.setWrapping(False)
        self.spinBox_J2.setFrame(True)
        self.spinBox_J2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J2.setMaximum(180)
        self.spinBox_J2.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J2, 1, 1, 1, 1)

        self.pushButton_J6 = QPushButton(self.gridWidget1)
        self.buttonGroup.addButton(self.pushButton_J6)
        self.pushButton_J6.setObjectName(u"pushButton_J6")
        self.pushButton_J6.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J6.sizePolicy().hasHeightForWidth())
        self.pushButton_J6.setSizePolicy(sizePolicy2)
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush21)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J6.setPalette(palette21)
        self.pushButton_J6.setFont(font)

        self.gridLayout_3.addWidget(self.pushButton_J6, 6, 0, 1, 1)

        self.spinBox_J5 = QSpinBox(self.gridWidget1)
        self.spinBox_J5.setObjectName(u"spinBox_J5")
        self.spinBox_J5.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J5.sizePolicy().hasHeightForWidth())
        self.spinBox_J5.setSizePolicy(sizePolicy2)
        self.spinBox_J5.setMinimumSize(QSize(90, 0))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.Button, brush28)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette22.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette22.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette22.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette22.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette22.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette22.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J5.setPalette(palette22)
        self.spinBox_J5.setFont(font6)
        self.spinBox_J5.setAutoFillBackground(False)
        self.spinBox_J5.setWrapping(False)
        self.spinBox_J5.setFrame(True)
        self.spinBox_J5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J5.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J5.setMaximum(180)
        self.spinBox_J5.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J5, 5, 1, 1, 1)

        self.pushButton_J4 = QPushButton(self.gridWidget1)
        self.buttonGroup.addButton(self.pushButton_J4)
        self.pushButton_J4.setObjectName(u"pushButton_J4")
        self.pushButton_J4.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J4.sizePolicy().hasHeightForWidth())
        self.pushButton_J4.setSizePolicy(sizePolicy2)
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush21)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette23.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J4.setPalette(palette23)
        self.pushButton_J4.setFont(font)

        self.gridLayout_3.addWidget(self.pushButton_J4, 3, 0, 1, 1)

        self.pushButton_J5 = QPushButton(self.gridWidget1)
        self.buttonGroup.addButton(self.pushButton_J5)
        self.pushButton_J5.setObjectName(u"pushButton_J5")
        self.pushButton_J5.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J5.sizePolicy().hasHeightForWidth())
        self.pushButton_J5.setSizePolicy(sizePolicy2)
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette24.setBrush(QPalette.Active, QPalette.Text, brush21)
        palette24.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette24.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette24.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J5.setPalette(palette24)
        self.pushButton_J5.setFont(font)

        self.gridLayout_3.addWidget(self.pushButton_J5, 5, 0, 1, 1)

        self.spinBox_J3 = QSpinBox(self.gridWidget1)
        self.spinBox_J3.setObjectName(u"spinBox_J3")
        self.spinBox_J3.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J3.sizePolicy().hasHeightForWidth())
        self.spinBox_J3.setSizePolicy(sizePolicy2)
        self.spinBox_J3.setMinimumSize(QSize(90, 0))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.Button, brush28)
        palette25.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette25.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette25.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette25.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette25.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette25.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette25.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette25.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J3.setPalette(palette25)
        self.spinBox_J3.setFont(font6)
        self.spinBox_J3.setAutoFillBackground(False)
        self.spinBox_J3.setWrapping(False)
        self.spinBox_J3.setFrame(True)
        self.spinBox_J3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J3.setMaximum(180)
        self.spinBox_J3.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J3, 2, 1, 1, 1)

        self.spinBox_J1 = QSpinBox(self.gridWidget1)
        self.spinBox_J1.setObjectName(u"spinBox_J1")
        self.spinBox_J1.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J1.sizePolicy().hasHeightForWidth())
        self.spinBox_J1.setSizePolicy(sizePolicy2)
        self.spinBox_J1.setMinimumSize(QSize(90, 0))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.Button, brush28)
        palette26.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette26.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette26.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette26.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette26.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette26.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette26.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette26.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J1.setPalette(palette26)
        self.spinBox_J1.setFont(font6)
        self.spinBox_J1.setAutoFillBackground(False)
        self.spinBox_J1.setWrapping(False)
        self.spinBox_J1.setFrame(True)
        self.spinBox_J1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J1.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J1.setMaximum(180)
        self.spinBox_J1.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J1, 0, 1, 1, 1)

        self.spinBox_J4 = QSpinBox(self.gridWidget1)
        self.spinBox_J4.setObjectName(u"spinBox_J4")
        self.spinBox_J4.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J4.sizePolicy().hasHeightForWidth())
        self.spinBox_J4.setSizePolicy(sizePolicy2)
        self.spinBox_J4.setMinimumSize(QSize(90, 0))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.Button, brush28)
        palette27.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette27.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette27.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette27.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette27.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette27.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette27.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette27.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette27.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette27.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J4.setPalette(palette27)
        self.spinBox_J4.setFont(font6)
        self.spinBox_J4.setAutoFillBackground(False)
        self.spinBox_J4.setWrapping(False)
        self.spinBox_J4.setFrame(True)
        self.spinBox_J4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J4.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J4.setMaximum(180)
        self.spinBox_J4.setValue(90)

        self.gridLayout_3.addWidget(self.spinBox_J4, 3, 1, 1, 1)

        self.spinBox_J6 = QSpinBox(self.gridWidget1)
        self.spinBox_J6.setObjectName(u"spinBox_J6")
        self.spinBox_J6.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.spinBox_J6.sizePolicy().hasHeightForWidth())
        self.spinBox_J6.setSizePolicy(sizePolicy2)
        self.spinBox_J6.setMinimumSize(QSize(90, 0))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.Button, brush28)
        palette28.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette28.setBrush(QPalette.Active, QPalette.Shadow, brush14)
        palette28.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette28.setBrush(QPalette.Inactive, QPalette.Button, brush28)
        palette28.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette28.setBrush(QPalette.Inactive, QPalette.Shadow, brush14)
        palette28.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette28.setBrush(QPalette.Disabled, QPalette.Button, brush28)
        palette28.setBrush(QPalette.Disabled, QPalette.Shadow, brush14)
        palette28.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        self.spinBox_J6.setPalette(palette28)
        self.spinBox_J6.setFont(font6)
        self.spinBox_J6.setAutoFillBackground(False)
        self.spinBox_J6.setWrapping(False)
        self.spinBox_J6.setFrame(True)
        self.spinBox_J6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_J6.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_J6.setMaximum(180)
        self.spinBox_J6.setValue(180)

        self.gridLayout_3.addWidget(self.spinBox_J6, 6, 1, 1, 1)

        self.pushButton_J3 = QPushButton(self.gridWidget1)
        self.buttonGroup.addButton(self.pushButton_J3)
        self.pushButton_J3.setObjectName(u"pushButton_J3")
        self.pushButton_J3.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_J3.sizePolicy().hasHeightForWidth())
        self.pushButton_J3.setSizePolicy(sizePolicy2)
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.WindowText, brush21)
        palette29.setBrush(QPalette.Active, QPalette.Button, brush26)
        palette29.setBrush(QPalette.Active, QPalette.Text, brush21)
        palette29.setBrush(QPalette.Active, QPalette.ButtonText, brush27)
        palette29.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette29.setBrush(QPalette.Inactive, QPalette.WindowText, brush21)
        palette29.setBrush(QPalette.Inactive, QPalette.Button, brush26)
        palette29.setBrush(QPalette.Inactive, QPalette.Text, brush21)
        palette29.setBrush(QPalette.Inactive, QPalette.ButtonText, brush27)
        palette29.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette29.setBrush(QPalette.Disabled, QPalette.Button, brush26)
        palette29.setBrush(QPalette.Disabled, QPalette.Text, brush21)
        palette29.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette29.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette29.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.pushButton_J3.setPalette(palette29)
        self.pushButton_J3.setFont(font)
        self.pushButton_J3.setStyleSheet(u"	QGroupBox::title {\n"
"				background-color: rgb(192, 184, 160);\n"
"	        }\n"
"")

        self.gridLayout_3.addWidget(self.pushButton_J3, 2, 0, 1, 1)

        self.pushButton = QPushButton(self.gridWidget1)
        self.pushButton.setObjectName(u"pushButton")
        palette30 = QPalette()
        brush30 = QBrush(QColor(170, 255, 255, 255))
        brush30.setStyle(Qt.SolidPattern)
        palette30.setBrush(QPalette.Active, QPalette.Button, brush30)
        palette30.setBrush(QPalette.Active, QPalette.ButtonText, brush29)
        palette30.setBrush(QPalette.Inactive, QPalette.Button, brush30)
        palette30.setBrush(QPalette.Inactive, QPalette.ButtonText, brush29)
        palette30.setBrush(QPalette.Disabled, QPalette.Button, brush30)
        self.pushButton.setPalette(palette30)
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(True)
        self.pushButton.setFont(font7)

        self.gridLayout_3.addWidget(self.pushButton, 7, 0, 1, 1)

        self.graphicsView = QGraphicsView(self.horizontalWidget_2)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(230, 40, 350, 250))
        sizePolicy2.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy2)
        self.graphicsView.setMinimumSize(QSize(100, 100))
        self.graphicsView.setMaximumSize(QSize(350, 400))
        palette31 = QPalette()
        brush31 = QBrush(QColor(186, 186, 186, 255))
        brush31.setStyle(Qt.SolidPattern)
        palette31.setBrush(QPalette.Active, QPalette.Base, brush31)
        palette31.setBrush(QPalette.Active, QPalette.Window, brush31)
        palette31.setBrush(QPalette.Inactive, QPalette.Base, brush31)
        palette31.setBrush(QPalette.Disabled, QPalette.Base, brush31)
        self.graphicsView.setPalette(palette31)
        self.graphicsView.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QFrame.Shape.Box)
        self.graphicsView.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView.setLineWidth(1)
        self.graphicsView.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView.setInteractive(True)

        self.gridLayout_2.addWidget(self.horizontalWidget_2, 4, 0, 1, 1)


        self.retranslateUi(LeafBotForm)

        self.pushButton_J1.setDefault(False)


        QMetaObject.connectSlotsByName(LeafBotForm)
    # setupUi

    def retranslateUi(self, LeafBotForm):
        LeafBotForm.setWindowTitle(QCoreApplication.translate("LeafBotForm", u"LeafBot", None))
        self.pushButton_3.setText(QCoreApplication.translate("LeafBotForm", u"Luanch All", None))
        self.LeafBotLogo.setText("")
        self.pushButton_21.setText(QCoreApplication.translate("LeafBotForm", u"Close All", None))
        self.label_2.setText(QCoreApplication.translate("LeafBotForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#248e00;\">LEAFBOT </span><span style=\" font-size:18pt; color:#ff0000;\">CONSOLE</span></p></body></html>", None))
        self.pushButton_move_forward.setText(QCoreApplication.translate("LeafBotForm", u"Move Forward", None))
        self.pushButton_set_torque.setText(QCoreApplication.translate("LeafBotForm", u"Set Torque", None))
        self.pushButton_read_servo.setText(QCoreApplication.translate("LeafBotForm", u"Read Servo", None))
        self.pushButton_park_to_plant.setText(QCoreApplication.translate("LeafBotForm", u"Park to Plant", None))
        self.pushButton_off_torque.setText(QCoreApplication.translate("LeafBotForm", u"Off Torque", None))
        self.pushButton_pick_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Pick Leaf", None))
        self.pushButton_detect_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Detect Leaf", None))
        self.pushButton_train_eye2hand.setText(QCoreApplication.translate("LeafBotForm", u"Train Eye2Hand", None))
        self.pushButton_move_backward.setText(QCoreApplication.translate("LeafBotForm", u"Move Backward", None))
        self.pushButton_segment_leaf.setText(QCoreApplication.translate("LeafBotForm", u"Segment Leaf", None))
        self.pushButton_zero_position.setText(QCoreApplication.translate("LeafBotForm", u"Zero Position", None))
        self.pushButton_Imitation.setText(QCoreApplication.translate("LeafBotForm", u"Imitation", None))
        self.toolButton.setText(QCoreApplication.translate("LeafBotForm", u"Update Joint List", None))
        self.pushButton_J2.setText(QCoreApplication.translate("LeafBotForm", u"J2", None))
        self.pushButton_J1.setText(QCoreApplication.translate("LeafBotForm", u"J1", None))
        self.pushButton_J6.setText(QCoreApplication.translate("LeafBotForm", u"J6", None))
        self.pushButton_J4.setText(QCoreApplication.translate("LeafBotForm", u"J4", None))
        self.pushButton_J5.setText(QCoreApplication.translate("LeafBotForm", u"J5", None))
        self.pushButton_J3.setText(QCoreApplication.translate("LeafBotForm", u"J3", None))
        self.pushButton.setText(QCoreApplication.translate("LeafBotForm", u"Move", None))
    # retranslateUi

